export const fishall = [
    { name: "ปลานิล", rarity: "ธรรมดา", price: 12, score: 1, rate: 45, status: "Active" },
    { name: "ปลาดุก", rarity: "ธรรมดา", price: 15, score: 1, rate: 40, status: "Active" },
    { name: "ปลาช่อน", rarity: "ธรรมดา", price: 20, score: 2, rate: 35, status: "Active" },
    { name: "ปลาสวาย", rarity: "ธรรมดา", price: 22, score: 2, rate: 30, status: "Active" },
    { name: "ปลากะพงขาว", rarity: "ธรรมดา", price: 25, score: 2, rate: 28, status: "Active" },
    { name: "ปลาตะเพียน", rarity: "ธรรมดา", price: 14, score: 1, rate: 42, status: "Active" },
    { name: "ปลาสลิด", rarity: "ธรรมดา", price: 18, score: 1, rate: 38, status: "Active" },
    { name: "ปลากริม", rarity: "ธรรมดา", price: 10, score: 1, rate: 48, status: "Active" },
    { name: "ปลากด", rarity: "ธรรมดา", price: 16, score: 1, rate: 40, status: "Active" },
    { name: "ปลาหมอไทย", rarity: "ธรรมดา", price: 13, score: 1, rate: 44, status: "Active" },
    { name: "ปลาหางนกยูง", rarity: "ธรรมดา", price: 12, score: 1, rate: 46, status: "Active" },
    { name: "ปลาซิว", rarity: "ธรรมดา", price: 9, score: 1, rate: 50, status: "Active" },
    { name: "ปลาทับทิม", rarity: "ธรรมดา", price: 21, score: 2, rate: 32, status: "Active" },
    { name: "ปลากระดี่", rarity: "ธรรมดา", price: 11, score: 1, rate: 47, status: "Active" },
    { name: "ปลาบู่", rarity: "ธรรมดา", price: 17, score: 1, rate: 39, status: "Active" },
    { name: "ปลากระมัง", rarity: "ธรรมดา", price: 15, score: 1, rate: 41, status: "Active" },
    { name: "ปลาดอลลี่", rarity: "ธรรมดา", price: 23, score: 2, rate: 29, status: "Active" },
    { name: "ปลาทรายแดง", rarity: "ธรรมดา", price: 19, score: 1, rate: 36, status: "Active" },
    { name: "ปลากรายจิ๋ว", rarity: "ธรรมดา", price: 18, score: 1, rate: 37, status: "Active" },
    { name: "ปลาค้อ", rarity: "ธรรมดา", price: 13, score: 1, rate: 43, status: "Active" },
    { name: "ปลากราย", rarity: "แรร์", price: 38, score: 3, rate: 22, status: "Active" },
    { name: "ปลากะพง", rarity: "แรร์", price: 45, score: 4, rate: 18, status: "Active" },
    { name: "ปลาทอง", rarity: "แรร์", price: 50, score: 5, rate: 15, status: "Active" },
    { name: "ปลาเทราต์", rarity: "แรร์", price: 55, score: 5, rate: 12, status: "Active" },
    { name: "ปลาการ์ตูน", rarity: "แรร์", price: 60, score: 6, rate: 10, status: "Active" },
    { name: "ปลาสลิดเงิน", rarity: "แรร์", price: 42, score: 3, rate: 20, status: "Active" },
    { name: "ปลาบึก", rarity: "แรร์", price: 70, score: 7, rate: 9, status: "Active" },
    { name: "ปลาเรนโบว์", rarity: "แรร์", price: 58, score: 5, rate: 11, status: "Active" },
    { name: "ปลาค็อด", rarity: "แรร์", price: 52, score: 4, rate: 13, status: "Active" },
    { name: "ปลาฮาเรน", rarity: "แรร์", price: 61, score: 6, rate: 10, status: "Active" },
    { name: "ปลาดอรี่", rarity: "แรร์", price: 57, score: 5, rate: 12, status: "Active" },
    { name: "ปลากีต้าร์", rarity: "แรร์", price: 65, score: 6, rate: 9.5, status: "Active" },
    { name: "ปลาแพะ", rarity: "แรร์", price: 48, score: 4, rate: 14, status: "Active" },
    { name: "ปลาหอกทะเล", rarity: "แรร์", price: 68, score: 6, rate: 9.2, status: "Active" },
    { name: "ปลากะพงแดง", rarity: "แรร์", price: 63, score: 6, rate: 9.8, status: "Active" },
    { name: "ปลาปักเป้า", rarity: "แรร์", price: 47, score: 4, rate: 14.5, status: "Active" },
    { name: "ปลากะพงทอง", rarity: "แรร์", price: 72, score: 7, rate: 8.8, status: "Active" },
    { name: "ปลาทูน่า", rarity: "อัลตร้าแรร์", price: 120, score: 10, rate: 8, status: "Active" },
    { name: "ปลามาร์ลิน", rarity: "อัลตร้าแรร์", price: 160, score: 14, rate: 6, status: "Active" },
    { name: "ฉลามหัวค้อน", rarity: "อัลตร้าแรร์", price: 200, score: 18, rate: 4, status: "Active" },
    { name: "ปลากระโทงดาบ", rarity: "อัลตร้าแรร์", price: 250, score: 20, rate: 3, status: "Active" },
    { name: "ฉลามเสือ", rarity: "อัลตร้าแรร์", price: 300, score: 25, rate: 2.5, status: "Active" },
    { name: "ปลากระเบนราหู", rarity: "อัลตร้าแรร์", price: 280, score: 22, rate: 3.2, status: "Active" },
    { name: "ปลาปิรันยาไจแอนท์", rarity: "อัลตร้าแรร์", price: 210, score: 17, rate: 3.6, status: "Active" },
    { name: "ปลากะรังยักษ์", rarity: "อัลตร้าแรร์", price: 190, score: 15, rate: 3.9, status: "Active" },
    { name: "ปลาดาบเงิน", rarity: "อัลตร้าแรร์", price: 230, score: 19, rate: 3.1, status: "Active" },
    { name: "ฉลามวาฬ", rarity: "อัลตร้าแรร์", price: 320, score: 28, rate: 2.2, status: "Active" },
    { name: "ปลาครีบใบมีด", rarity: "อัลตร้าแรร์", price: 260, score: 21, rate: 2.8, status: "Active" },
    { name: "ปลากะพงจักรพรรดิ", rarity: "อัลตร้าแรร์", price: 240, score: 20, rate: 3.0, status: "Active" },
    { name: "มังกรน้ำ", rarity: "ตำนาน", price: 600, score: 60, rate: 1, status: "Active" },
    { name: "คราเคน", rarity: "ตำนาน", price: 900, score: 90, rate: 0.9, status: "Active" },
    { name: "พญานาค", rarity: "ตำนาน", price: 1500, score: 90, rate: 0.8, status: "Active" },
    { name: "จระเข้ยักษ์", rarity: "ตำนาน", price: 1600, score: 95, rate: 0.8, status: "Active" },
    { name: "เต่ายักษ์พันปี", rarity: "ตำนาน", price: 1650, score: 95, rate: 0.7, status: "Active" },
    { name: "งูทะเลเพลิง", rarity: "ตำนาน", price: 1700, score: 100, rate: 0.7, status: "Active" },
    { name: "ฉลามเพชฌฆาตวิญญาณ", rarity: "ตำนาน", price: 1750, score: 105, rate: 0.6, status: "Active" },
    { name: "ปลาวาฬคริสตัล", rarity: "ตำนาน", price: 1780, score: 106, rate: 0.6, status: "Active" },
    { name: "ปลากระเบนสายฟ้า", rarity: "ตำนาน", price: 1800, score: 107, rate: 0.6, status: "Active" },
    { name: "มังกรน้ำแข็งลึก", rarity: "ตำนาน", price: 1820, score: 108, rate: 0.5, status: "Active" },
    { name: "ปลาฟีนิกซ์น้ำ", rarity: "เทพนิยาย", price: 2200, score: 140, rate: 0.08, status: "Active" },
    { name: "คิเมร่าน้ำ", rarity: "เทพนิยาย", price: 2600, score: 160, rate: 0.07, status: "Active" },
    { name: "คริสตัลคอย", rarity: "เทพนิยาย", price: 3000, score: 180, rate: 0.07, status: "Active" },
    { name: "เซราฟิมอควา", rarity: "เทพนิยาย", price: 3600, score: 200, rate: 0.06, status: "Active" },
    { name: "ปลาดาวสุริยันต์", rarity: "เทพนิยาย", price: 4200, score: 220, rate: 0.06, status: "Active" },
    { name: "คาร์พอัญมณี", rarity: "เทพนิยาย", price: 5000, score: 250, rate: 0.06, status: "Active" },
    { name: "มังกรคาบเพชร", rarity: "เทพนิยาย", price: 6500, score: 300, rate: 0.05, status: "Active" },
    { name: "เงือกมุกแดง", rarity: "เทพนิยาย", price: 8000, score: 360, rate: 0.05, status: "Active" },
    { name: "ราชานาคเรนโบว์", rarity: "สายรุ้ง", price: 15000, score: 480, rate: 0.03, status: "Active" },
    { name: "HBD Admin Boat", rarity: "สายรุ้ง", price: 10000, score: 480, rate: 0.5, status: "UnActive" },
    { name: "ปลาแจ็กโอแลนเทิร์น", rarity: "สายรุ้ง", price: 10000, score: 480, rate: 0.3, status: "UnActive" },
    { name: "คราเคนเจ็ดสี", rarity: "สายรุ้ง", price: 45000, score: 560, rate: 0.01, status: "Active" },
    { name: "มังกรมหาเทพรุ้ง", rarity: "สายรุ้ง", price: 45000, score: 560, rate: 0.01, status: "Active" },
    { name: "ปลากระป๋องหมดอายุ", rarity: "สายรุ้ง", price: 45000, score: 560, rate: 0.01, status: "Active" },
    { name: "เขียดตะปาดขาดวิตามิน", rarity: "สายรุ้ง", price: 45000, score: 560, rate: 0.01, status: "Active" },
    { name: "ปลาสุดหล่อมองท่อไม่มองทาง", rarity: "สายรุ้ง", price: 45000, score: 560, rate: 0.01, status: "Active" },
    { name: "ปลาทังก้าปลาทังกี้", rarity: "สายรุ้ง", price: 45000, score: 560, rate: 0.01, status: "Active" },
    { name: "ปลาคราฟจักรพรรดิ์เรนโบว์", rarity: "สายรุ้ง", price: 150000, score: 1560, rate: 0.003, status: "Active" },
    { name: "วาฬจักรวาลสีรุ้ง", rarity: "สายรุ้ง", price: 200000, score: 650, rate: 0.002, status: "Active" },
    { name: "ปลาTeenสีรุ้ง", rarity: "สายรุ้ง", price: 150000, score: 650, rate: 0.006, status: "Active" },
]
export const trashall = [
    { name: "สาหร่าย", type: "trash", rate: 14 },
    { name: "รองเท้าเก่า", type: "trash", rate: 10 },
    { name: "ไม้ซีก", type: "trash", rate: 10 },
    { name: "ฝาขวด", type: "trash", rate: 8 },
    { name: "พลาสติกขยำ", type: "trash", rate: 8 },
    { name: "กระป๋องขึ้นสนิม", type: "trash", rate: 7 },
    { name: "สายเบ็ดขาด", type: "trash", rate: 6 },
    { name: "ว่างเปล่า", type: "nothing", rate: 12 },
]

export const fishgiveitem = [
    { fishname: "ราชานาคเรนโบว์", itemname: "ปืนฉลามฟองสบู่", itemimage: "/images/items/SharkBubbleGun.png" },
    { fishname: "HBD Admin Boat", itemname: "ปืนเลเซอร์", itemimage: "/images/items/LaserGun.png" },
    { fishname: "ปลาแจ็กโอแลนเทิร์น", itemname: "เบ็ดฮัลโลวีน", itemimage: "/images/items/HalloweenRod.png" },
    { fishname: "คราเคนเจ็ดสี", itemname: "ป้ายข้อความ", itemimage: "/images/items/Textboard.png" },
    { fishname: "มังกรมหาเทพรุ้ง", itemname: "อัญเชิญจักรยาน", itemimage: "/images/items/BmxTool.png" },
    { fishname: "ปลากระป๋องหมดอายุ", itemname: "อัญเชิญมอไซค์Wave110", itemimage: "/images/items/MotorWave110Tool.png" },
    { fishname: "เขียดตะปาดขาดวิตามิน", itemname: "อัญเชิญมอไซค์Wave125i", itemimage: "/images/items/MotorWave125iTool.png" },
    { fishname: "ปลาสุดหล่อมองท่อไม่มองทาง", itemname: "อัญเชิญมอไซค์Wave125s", itemimage: "/images/items/MotorWave125sTool.png" },
    { fishname: "ปลาทังก้าปลาทังกี้", itemname: "อัญเชิญมอไซค์ZoomerX", itemimage: "/images/items/MotorZoomerXTool.png" },
    { fishname: "ปลาคราฟจักรพรรดิ์เรนโบว์", itemname: "เก้าอี้ซากุระชิงช้า", itemimage: "/images/items/ChairSakuratreeswingTool.png" },
    { fishname: "ปลาTeenสีรุ้ง", itemname: "ขมับแม่ม", itemimage: "/images/items/SlipperSlap.png" },
    { fishname: "วาฬจักรวาลสีรุ้ง", itemname: "ตู้ปลาหรรษาเล็ก", itemimage: "/images/items/FishTankSmallTool.png" },
]
export const rodall = [
    { rodname: "คันเบ็ด", rodimage: "/images/items/FishingRod.png", cooldown: "15", Luck: "100%", money: "100%", Score: "100%" },
    { rodname: "คันเบ็ด (VIP)", rodimage: "/images/items/VIPFishingRod.png", cooldown: "12", Luck: "200%", money: "200%", Score: "200%" },
    { rodname: "เบ็ดฮัลโลวีน", rodimage: "/images/items/HalloweenRod.png", cooldown: "15", Luck: "700%", money: "110%", Score: "110%" },
    { rodname: "เบ็ดฮัลโลวีนพรีเมี่ยม", rodimage: "/images/items/LuckyHalloweenRod.png", cooldown: "14", Luck: "1000%", money: "130%", Score: "130%" },
]