// กาชา (FarmConfig.Gacha) — pool + น้ำหนัก (weight) ของแต่ละชิ้น
// อัตราออก (%) = weight ของชิ้นนั้น / ผลรวม weight ทั้ง pool  (คำนวณในหน้าเว็บ)

export const gachaRarities = {
  Common: { order: 1, label: "ธรรมดา" },
  Uncommon: { order: 2, label: "ไม่ธรรมดา" },
  Rare: { order: 3, label: "หายาก" },
  Epic: { order: 4, label: "หายากมาก" },
  Legendary: { order: 5, label: "ตำนาน" },
};

// source: how you get the box to open this pool
export const gachaPools = [
  {
    key: "Doll",
    boxItem: "DollGachaBox",
    displayName: "กาชาตุ๊กตา V1",
    price: 10000,
    source: "ซื้อกล่องในร้าน / คราฟที่โต๊ะคราฟ",
    items: [
      { item: "Bunnydoll", rarity: "Common", weight: 60 },
      { item: "Minion", rarity: "Uncommon", weight: 40 },
      { item: "Godji", rarity: "Rare", weight: 20 },
      { item: "Rice", rarity: "Epic", weight: 10, min: 1, max: 2 },
      { item: "HelloKitty", rarity: "Epic", weight: 8 },
      { item: "KittyLove", rarity: "Epic", weight: 8 },
      { item: "mymelody_Beta", rarity: "Legendary", weight: 2 },
      { item: "kuromi_Beta", rarity: "Legendary", weight: 2 },
    ],
  },
  {
    key: "Chair",
    boxItem: "ChairGachaBox",
    displayName: "กาชาเก้าอี้ V1",
    price: 80000,
    source: "ซื้อกล่องในร้าน / คราฟที่โต๊ะคราฟ",
    items: [
      { item: "RedPlasticChairTool", rarity: "Common", weight: 60 },
      { item: "ChairSpongeTool", rarity: "Common", weight: 50 },
      { item: "ChairstrawberryTool", rarity: "Uncommon", weight: 30 },
      { item: "ChairLoveWhiteTool", rarity: "Uncommon", weight: 30 },
      { item: "ChairPinkRabbitTool", rarity: "Uncommon", weight: 25 },
      { item: "ChairKuromiTool", rarity: "Rare", weight: 15 },
      { item: "ChairMymelodyTool", rarity: "Rare", weight: 15 },
      { item: "Rice", rarity: "Epic", weight: 10, min: 5, max: 10 },
      { item: "ChairTwoPersonTool", rarity: "Epic", weight: 9 },
      { item: "ChairRoyalTool", rarity: "Epic", weight: 9 },
      { item: "RiceTop", rarity: "Legendary", weight: 4, min: 2, max: 5 },
      { item: "ChairGamingRGBTool", rarity: "Legendary", weight: 2 },
      { item: "ChairSakuratreeswingTool", rarity: "Legendary", weight: 0.5 },
    ],
  },
  {
    key: "PetGacha",
    boxItem: "PetGachaBox",
    displayName: "กาชาสัตว์เลี้ยง",
    price: 30000000,
    source: "ซื้อกล่องในร้าน / คราฟที่โต๊ะคราฟ",
    items: [
      { item: "Bunny", isPet: true, rarity: "Common", weight: 100 },
      { item: "SharkPet", isPet: true, rarity: "Uncommon", weight: 100 },
      { item: "Dog", isPet: true, rarity: "Uncommon", weight: 100 },
      { item: "frog", isPet: true, rarity: "Rare", weight: 100 },
      { item: "Chicken", isPet: true, rarity: "Rare", weight: 100 },
      { item: "Cat", isPet: true, rarity: "Epic", weight: 100 },
      { item: "DarkDevil", isPet: true, rarity: "Legendary", weight: 20 },
      { item: "404Demon", isPet: true, rarity: "Legendary", weight: 5 },
    ],
  },
  {
    key: "Season",
    boxItem: "SeasonGachaBox",
    displayName: "กาชาไอเทมซีซั่น",
    source: "คราฟที่โต๊ะคราฟ",
    items: [
      { item: "Rice", rarity: "Common", weight: 60, min: 5, max: 15 },
      { item: "Money", rarity: "Uncommon", weight: 35, min: 2000, max: 8000 },
      { item: "Iron", rarity: "Rare", weight: 20, min: 1, max: 3 },
      { item: "RiceTop", rarity: "Rare", weight: 20, min: 1, max: 3 },
      { item: "Rope", rarity: "Epic", weight: 3 },
      { item: "RibbonRope", rarity: "Epic", weight: 3 },
      { item: "FrozenHammer", rarity: "Epic", weight: 3 },
      { item: "BaseBallss3", rarity: "Legendary", weight: 2.5 },
      { item: "SniperGun", rarity: "Legendary", weight: 2.5 },
    ],
  },
  {
    key: "Event",
    boxItem: "EventGachaBox",
    displayName: "กาชา Event",
    source: "Airdrop รายชั่วโมง / รางวัลบอสโลก",
    items: [
      { item: "Rice", rarity: "Common", weight: 80, min: 3, max: 5 },
      { item: "Money", rarity: "Uncommon", weight: 30, min: 1000, max: 5000 },
      { item: "RiceTop", rarity: "Rare", weight: 10, min: 1, max: 3 },
      { item: "Iron", rarity: "Rare", weight: 6, min: 1, max: 2 },
      { item: "GoldenTicket", rarity: "Epic", weight: 3, min: 1, max: 2 },
      { item: "LuckyCraftTicket", rarity: "Legendary", weight: 1, min: 1, max: 1 },
      { item: "GuaranteeCraftTicket", rarity: "Legendary", weight: 0.05, min: 1, max: 1 },
    ],
  },
  {
    key: "Admin",
    boxItem: "AdminGachaBox",
    displayName: "กาชา Admin",
    source: "รางวัลบอสโลก (ตัวพิเศษ)",
    items: [
      { item: "Rice", rarity: "Common", weight: 70, min: 3, max: 10 },
      { item: "Money", rarity: "Uncommon", weight: 30, min: 5000, max: 10000 },
      { item: "RiceTop", rarity: "Rare", weight: 10, min: 1, max: 5 },
      { item: "Iron", rarity: "Rare", weight: 6, min: 1, max: 3 },
      { item: "GoldenTicket", rarity: "Epic", weight: 3, min: 2, max: 5 },
      { item: "LuckyCraftTicket", rarity: "Legendary", weight: 1, min: 1, max: 2 },
      { item: "GuaranteeCraftTicket", rarity: "Legendary", weight: 0.08, min: 1, max: 1 },
    ],
  },
  {
    key: "SadnoobBossGacha",
    boxItem: "SadnoobBossGachaBox",
    displayName: "กาชาบอส SadNoob",
    source: "รางวัลบอส SadNoob",
    items: [
      { item: "Rice", rarity: "Common", weight: 80, min: 3, max: 5 },
      { item: "Money", rarity: "Uncommon", weight: 30, min: 1000, max: 5000 },
      { item: "RiceTop", rarity: "Rare", weight: 10, min: 1, max: 3 },
      { item: "Iron", rarity: "Rare", weight: 6, min: 1, max: 2 },
      { item: "GoldenTicket", rarity: "Epic", weight: 3, min: 1, max: 2 },
      { item: "LuckyCraftTicket", rarity: "Legendary", weight: 1, min: 1, max: 1 },
      { item: "GuaranteeCraftTicket", rarity: "Legendary", weight: 0.05, min: 1, max: 1 },
      { item: "Rainbowwing", rarity: "Legendary", weight: 0.03 },
    ],
  },
  {
    key: "DecorV1",
    boxItem: "DecorGachaBox",
    displayName: "กาชาของตกแต่งv1",
    price: 0,
    source: "คราฟที่โต๊ะคราฟ (ไม่ขายในร้าน)",
    craftOnly: true,
    items: [
      { item: "BalloonsTool", rarity: "Common", weight: 100 },
      { item: "PicnicBasketTool", rarity: "Common", weight: 90 },
      { item: "PoolFloatTool", rarity: "Uncommon", weight: 60 },
      { item: "StableTool", rarity: "Uncommon", weight: 55 },
      { item: "TableParty4Tool", rarity: "Rare", weight: 35 },
      { item: "PartyTable6Tool", rarity: "Rare", weight: 32 },
      { item: "DiscoTool", rarity: "Rare", weight: 30 },
      { item: "GrillTool", rarity: "Epic", weight: 15 },
      { item: "BalloonDoorTool", rarity: "Epic", weight: 12 },
      { item: "BlueConfettiTool", rarity: "Legendary", weight: 6 },
      { item: "PurpleConfettiTool", rarity: "Legendary", weight: 6 },
      { item: "SmokeMachineTool", rarity: "Legendary", weight: 3 },
    ],
  },
  {
    key: "BubbleSkin",
    boxItem: "BubbleSkinGachaBox",
    displayName: "กาชาฟองคำพูด",
    price: 0,
    source: "คราฟที่โต๊ะคราฟ (ไม่ขายในร้าน)",
    craftOnly: true,
    note: "เปิดแล้วปลดล็อกสกินฟองคำพูดถาวรทันที · เทรดไม่ได้ · ได้ซ้ำคืนเงิน 150,000 · เปลี่ยนฟองได้ที่มือถือ › 📱 ทั่วไป › 🗨️ ฟองคำพูด",
    items: [
      { item: "BubbleSkin_sweetcandy", display: "🍬 ฟองลูกกวาดหวานเจี๊ยบ", img: "/images/bubbleskin/sweetcandy.png", rarity: "Common", weight: 7.86 },
      { item: "BubbleSkin_snow", display: "❄️ ฟองหิมะ", img: "/images/bubbleskin/snow.png", rarity: "Common", weight: 7.86 },
      { item: "BubbleSkin_tama", display: "🥚 ฟองทามาก็อต", img: "/images/bubbleskin/tama.png", rarity: "Common", weight: 7.86 },
      { item: "BubbleSkin_sakura", display: "🌸 ฟองซากุระบาน", img: "/images/bubbleskin/sakura.png", rarity: "Common", weight: 7.86 },
      { item: "BubbleSkin_ocean", display: "🌊 ฟองทะเลใสฟ้าคราม", img: "/images/bubbleskin/ocean.png", rarity: "Common", weight: 7.86 },
      { item: "BubbleSkin_cloud", display: "☁️ ฟองปุยเมฆลอยฟ้า", img: "/images/bubbleskin/cloud.png", rarity: "Common", weight: 7.85 },
      { item: "BubbleSkin_icecream", display: "🍦 ฟองไอศกรีมพาสเทล", img: "/images/bubbleskin/icecream.png", rarity: "Common", weight: 7.85 },
      { item: "BubbleSkin_love", display: "💞 ฟองคู่รัก", img: "/images/bubbleskin/love.png", rarity: "Uncommon", weight: 4.29 },
      { item: "BubbleSkin_bday", display: "🎂 ฟองวันเกิด", img: "/images/bubbleskin/bday.png", rarity: "Uncommon", weight: 4.29 },
      { item: "BubbleSkin_mind", display: "🎯 ฟองนักถอดรหัส", img: "/images/bubbleskin/mind.png", rarity: "Uncommon", weight: 4.29 },
      { item: "BubbleSkin_forest", display: "🍀 ฟองสวนป่าใบไม้", img: "/images/bubbleskin/forest.png", rarity: "Uncommon", weight: 4.29 },
      { item: "BubbleSkin_kitty", display: "🐱 ฟองแมวเหมียวขี้อ้อน", img: "/images/bubbleskin/kitty.png", rarity: "Uncommon", weight: 4.28 },
      { item: "BubbleSkin_music", display: "🎤 ฟองนักร้องเสียงใส", img: "/images/bubbleskin/music.png", rarity: "Uncommon", weight: 4.28 },
      { item: "BubbleSkin_autumn", display: "🍁 ฟองใบไม้ร่วง", img: "/images/bubbleskin/autumn.png", rarity: "Uncommon", weight: 4.28 },
      { item: "BubbleSkin_halloween", display: "🎃 ฟองฮาโลวีน", img: "/images/bubbleskin/halloween.png", rarity: "Rare", weight: 2.4 },
      { item: "BubbleSkin_goldrich", display: "🏅 ฟองเศรษฐีทอง", img: "/images/bubbleskin/goldrich.png", rarity: "Rare", weight: 2.4 },
      { item: "BubbleSkin_space", display: "🚀 ฟองอวกาศจรวดน้อย", img: "/images/bubbleskin/space.png", rarity: "Rare", weight: 2.4 },
      { item: "BubbleSkin_dragon", display: "🐉 ฟองมังกรทองนำโชค", img: "/images/bubbleskin/dragon.png", rarity: "Rare", weight: 2.4 },
      { item: "BubbleSkin_neon", display: "⚡ ฟองนีออนไซเบอร์", img: "/images/bubbleskin/neon.png", rarity: "Rare", weight: 2.4 },
      { item: "BubbleSkin_rainbow", display: "🌈 ฟองสายรุ้ง", img: "/images/bubbleskin/rainbow.png", rarity: "Epic", weight: 0.84 },
      { item: "BubbleSkin_unicorn", display: "🦄 ฟองยูนิคอร์นพาสเทล", img: "/images/bubbleskin/unicorn.png", rarity: "Epic", weight: 0.83 },
      { item: "BubbleSkin_aurora", display: "🌌 ฟองแสงเหนือ", img: "/images/bubbleskin/aurora.png", rarity: "Epic", weight: 0.83 },
      { item: "BubbleSkin_platinum", display: "🥇 ฟองทองคำขาวเจ้าสวรรค์", img: "/images/bubbleskin/platinum.png", rarity: "Legendary", weight: 0.17 },
      { item: "BubbleSkin_angel", display: "👼 ฟองนางฟ้าสวรรค์", img: "/images/bubbleskin/angel.png", rarity: "Legendary", weight: 0.17 },
      { item: "BubbleSkin_devil", display: "😈 ฟองราชาปีศาจ", img: "/images/bubbleskin/devil.png", rarity: "Legendary", weight: 0.16 },
    ],
  },
];

export const gachaMeta = { rollSeconds: 10, maxPerBuy: 50 };
