// กาชา (FarmConfig.Gacha) — pool + น้ำหนัก (weight) ของแต่ละชิ้น
// อัตราออก (%) = weight ของชิ้นนั้น / ผลรวม weight ทั้ง pool  (คำนวณในหน้าเว็บ)

export const gachaRarities = {
  Common: { order: 1, label: "ธรรมดา" },
  Uncommon: { order: 2, label: "ไม่ธรรมดา" },
  Rare: { order: 3, label: "หายาก" },
  Epic: { order: 4, label: "หายากมาก" },
  Legendary: { order: 5, label: "ตำนาน" },
};

// source: how you get the box to open this pool
export const gachaPools = [
  {
    key: "Doll",
    boxItem: "DollGachaBox",
    displayName: "กาชาตุ๊กตา V1",
    price: 10000,
    source: "ซื้อกล่องในร้าน / คราฟที่โต๊ะคราฟ",
    items: [
      { item: "Bunnydoll", rarity: "Common", weight: 60 },
      { item: "Minion", rarity: "Uncommon", weight: 40 },
      { item: "Godji", rarity: "Rare", weight: 20 },
      { item: "Rice", rarity: "Epic", weight: 10, min: 1, max: 2 },
      { item: "HelloKitty", rarity: "Epic", weight: 8 },
      { item: "KittyLove", rarity: "Epic", weight: 8 },
      { item: "mymelody_Beta", rarity: "Legendary", weight: 2 },
      { item: "kuromi_Beta", rarity: "Legendary", weight: 2 },
    ],
  },
  {
    key: "Chair",
    boxItem: "ChairGachaBox",
    displayName: "กาชาเก้าอี้ V1",
    price: 80000,
    source: "ซื้อกล่องในร้าน / คราฟที่โต๊ะคราฟ",
    items: [
      { item: "RedPlasticChairTool", rarity: "Common", weight: 60 },
      { item: "ChairSpongeTool", rarity: "Common", weight: 50 },
      { item: "ChairstrawberryTool", rarity: "Uncommon", weight: 30 },
      { item: "ChairLoveWhiteTool", rarity: "Uncommon", weight: 30 },
      { item: "ChairPinkRabbitTool", rarity: "Uncommon", weight: 25 },
      { item: "ChairKuromiTool", rarity: "Rare", weight: 15 },
      { item: "ChairMymelodyTool", rarity: "Rare", weight: 15 },
      { item: "Rice", rarity: "Epic", weight: 10, min: 5, max: 10 },
      { item: "ChairTwoPersonTool", rarity: "Epic", weight: 9 },
      { item: "ChairRoyalTool", rarity: "Epic", weight: 9 },
      { item: "RiceTop", rarity: "Legendary", weight: 4, min: 2, max: 5 },
      { item: "ChairGamingRGBTool", rarity: "Legendary", weight: 2 },
      { item: "ChairSakuratreeswingTool", rarity: "Legendary", weight: 0.5 },
    ],
  },
  {
    key: "PetGacha",
    boxItem: "PetGachaBox",
    displayName: "กาชาสัตว์เลี้ยง",
    price: 30000000,
    source: "ซื้อกล่องในร้าน / คราฟที่โต๊ะคราฟ",
    items: [
      { item: "Bunny", isPet: true, rarity: "Common", weight: 100 },
      { item: "SharkPet", isPet: true, rarity: "Uncommon", weight: 100 },
      { item: "Dog", isPet: true, rarity: "Uncommon", weight: 100 },
      { item: "frog", isPet: true, rarity: "Rare", weight: 100 },
      { item: "Chicken", isPet: true, rarity: "Rare", weight: 100 },
      { item: "Cat", isPet: true, rarity: "Epic", weight: 100 },
      { item: "DarkDevil", isPet: true, rarity: "Legendary", weight: 20 },
      { item: "404Demon", isPet: true, rarity: "Legendary", weight: 5 },
    ],
  },
  {
    key: "Season",
    boxItem: "SeasonGachaBox",
    displayName: "กาชาไอเทมซีซั่น",
    source: "คราฟที่โต๊ะคราฟ",
    items: [
      { item: "Rice", rarity: "Common", weight: 60, min: 5, max: 15 },
      { item: "Money", rarity: "Uncommon", weight: 35, min: 2000, max: 8000 },
      { item: "Iron", rarity: "Rare", weight: 20, min: 1, max: 3 },
      { item: "RiceTop", rarity: "Rare", weight: 20, min: 1, max: 3 },
      { item: "Rope", rarity: "Epic", weight: 3 },
      { item: "RibbonRope", rarity: "Epic", weight: 3 },
      { item: "FrozenHammer", rarity: "Epic", weight: 3 },
      { item: "BaseBallss3", rarity: "Legendary", weight: 2.5 },
      { item: "SniperGun", rarity: "Legendary", weight: 2.5 },
    ],
  },
  {
    key: "Event",
    boxItem: "EventGachaBox",
    displayName: "กาชา Event",
    source: "Airdrop รายชั่วโมง / รางวัลบอสโลก",
    items: [
      { item: "Rice", rarity: "Common", weight: 80, min: 3, max: 5 },
      { item: "Money", rarity: "Uncommon", weight: 30, min: 1000, max: 5000 },
      { item: "RiceTop", rarity: "Rare", weight: 10, min: 1, max: 3 },
      { item: "Iron", rarity: "Rare", weight: 6, min: 1, max: 2 },
      { item: "GoldenTicket", rarity: "Epic", weight: 3, min: 1, max: 2 },
      { item: "LuckyCraftTicket", rarity: "Legendary", weight: 1, min: 1, max: 1 },
      { item: "GuaranteeCraftTicket", rarity: "Legendary", weight: 0.05, min: 1, max: 1 },
    ],
  },
  {
    key: "Admin",
    boxItem: "AdminGachaBox",
    displayName: "กาชา Admin",
    source: "รางวัลบอสโลก (ตัวพิเศษ)",
    items: [
      { item: "Rice", rarity: "Common", weight: 70, min: 3, max: 10 },
      { item: "Money", rarity: "Uncommon", weight: 30, min: 5000, max: 10000 },
      { item: "RiceTop", rarity: "Rare", weight: 10, min: 1, max: 5 },
      { item: "Iron", rarity: "Rare", weight: 6, min: 1, max: 3 },
      { item: "GoldenTicket", rarity: "Epic", weight: 3, min: 2, max: 5 },
      { item: "LuckyCraftTicket", rarity: "Legendary", weight: 1, min: 1, max: 2 },
      { item: "GuaranteeCraftTicket", rarity: "Legendary", weight: 0.08, min: 1, max: 1 },
    ],
  },
  {
    key: "SadnoobBossGacha",
    boxItem: "SadnoobBossGachaBox",
    displayName: "กาชาบอส SadNoob",
    source: "รางวัลบอส SadNoob",
    items: [
      { item: "Rice", rarity: "Common", weight: 80, min: 3, max: 5 },
      { item: "Money", rarity: "Uncommon", weight: 30, min: 1000, max: 5000 },
      { item: "RiceTop", rarity: "Rare", weight: 10, min: 1, max: 3 },
      { item: "Iron", rarity: "Rare", weight: 6, min: 1, max: 2 },
      { item: "GoldenTicket", rarity: "Epic", weight: 3, min: 1, max: 2 },
      { item: "LuckyCraftTicket", rarity: "Legendary", weight: 1, min: 1, max: 1 },
      { item: "GuaranteeCraftTicket", rarity: "Legendary", weight: 0.05, min: 1, max: 1 },
      { item: "Rainbowwing", rarity: "Legendary", weight: 0.03 },
    ],
  },
];

export const gachaMeta = { rollSeconds: 10, maxPerBuy: 50 };
