export const itemall = [
    {
        "code": "FishingRod",
        "nameTH": "คันเบ็ด",
        "icon": "/images/items/FishingRod.png",
        "detail": "เบ็ดตกปลาเริ่มต้น",
        "grouptype": "เบ็ด",
        "getby": "ไอเท็มเริ่มต้น",
    },
    {
        "code": "VIPFishingRod",
        "nameTH": "คันเบ็ด (VIP)",
        "icon": "/images/items/VIPFishingRod.png",
        "detail": "ซื้อ Pass Vip ได้รับเบ็ดตกปลาที่บลานซ์ที่สุด โชค เงิน ระยะเวลาการตกปลา",
        "grouptype": "เบ็ด",
        "getby": "ซื้อ Pass",
    },
    {
        "code": "Slapuncommon",
        "nameTH": "ตบ",
        "icon": "/images/items/Slapuncommon.png",
        "detail": "มือตบเริ่มต้น+สกิลตด คลูดาวน์ ตบ 10 นาที สกิล 1 นาที",
        "grouptype": "มือตบ",
        "getby": "ไอเท็มเริ่มต้น",
    },
    {
        "code": "SlapBlind",
        "nameTH": "ตบบอด",
        "icon": "/images/items/SlapBlind.png",
        "detail": "มือตบตาบอด+สกิลจอดำ คลูดาวน์ ตบ 1 นาที 30 วินาที สกิล  1 นาที 30 วินาที",
        "grouptype": "มือตบ",
        "getby": "ซื้อ Pass",
    },
    {
        "code": "SlapSpin",
        "nameTH": "ตบหมุน",
        "icon": "/images/items/SlapSpin.png",
        "detail": "มือตบหัวหมุน+สกิลจอหมุน คลูดาวน์ ตบ 1 นาที 20 วินาที สกิล  1 นาที 20 วินาที",
        "grouptype": "มือตบ",
        "getby": "ซื้อ Pass",
    },
    {
        "code": "Sudoku",
        "nameTH": "ซูโดกุ",
        "icon": "/images/items/Sudoku.png",
        "detail": "เกมซูโดกุ ใช้หาเงิน และเล่นแก้เบื่อ",
        "grouptype": "ทั่วไป",
        "getby": "ไอเท็มเริ่มต้น",
    },
    {
        "code": "Lantern",
        "nameTH": "โคมไฟ",
        "icon": "/images/items/Lantern.png",
        "detail": "ใช้ส่องสว่างในที่มืด สามารถปรับความสว่าง และสีได้",
        "grouptype": "ทั่วไป",
        "getby": "ไอเท็มเริ่มต้น",
    },
    {
        "code": "Sparkler",
        "nameTH": "ดอกไม้ไฟ",
        "icon": "/images/items/Sparkler.png",
        "detail": "ใช้ส่องสว่าง ไว้นำทาให้เพื่อนๆสามารถเดินตามได้ถูก สามารถปรับสีได้",
        "grouptype": "ทั่วไป",
        "getby": "ไอเท็มเริ่มต้น",
    },
    {
        "code": "Matching",
        "nameTH": "จับคู่",
        "icon": "/images/items/Matching.png",
        "detail": "แอพหาคู่ ที่คนส่วนใหญ่ไม่เล่น เนื่องจากเปลืองตังค์",
        "grouptype": "ทั่วไป",
        "getby": "ไอเท็มเริ่มต้น",
    },
    {
        "code": "mymelody_Beta",
        "nameTH": "มายเมโลดี้ (Beta)",
        "icon": "/images/items/mymelody_Beta.png",
        "detail": "ตุ๊กตาที่ใช้บ่งบอกความเป็นผู้เล่นยุคบุกเบิก",
        "grouptype": "ตุ๊กตา",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "kuromi_Beta",
        "nameTH": "คุโรมิ (Beta)",
        "icon": "/images/items/kuromi_Beta.png",
        "detail": "ตุ๊กตาที่ใช้บ่งบอกความเป็นผู้เล่นยุคบุกเบิก",
        "grouptype": "ตุ๊กตา",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "Lightsaber",
        "nameTH": "ดาบแสง",
        "icon": "/images/items/Lightsaber.png",
        "detail": "ดาบที่ใช้แกว่งเพื่อนความสวยงาม เลือกสี และเปิด-ปิดได้",
        "grouptype": "ทั่วไป",
        "getby": "ไอเท็มเริ่มต้น",
    },
    {
        "code": "GuessStick",
        "nameTH": "ทายคำ",
        "icon": "/images/items/GuessStick.png",
        "detail": "เกมทายคำ",
        "grouptype": "ทั่วไป",
        "getby": "ไอเท็มเริ่มต้น",
    },
    {
        "code": "ForbiddenStick",
        "nameTH": "คำต้องห้าม",
        "icon": "/images/items/ForbiddenStick.png",
        "detail": "เกมคำต้องห้าม",
        "grouptype": "ทั่วไป",
        "getby": "ไอเท็มเริ่มต้น",
    },
    {
        "code": "Torch",
        "nameTH": "ไฟวิ่งแบบพี่ตูน",
        "icon": "/images/items/Torch.png",
        "detail": "เมื่อถือ ความเร็บในการวิ่งจะเพิ่มเป็น 80",
        "grouptype": "เดินทาง",
        "getby": "ซื้อ Pass",
    },
    {
        "code": "TorchLimited",
        "nameTH": "คบไฟบรรลัยกัลป์",
        "icon": "/images/items/TorchLimited.png",
        "detail": "เมื่อถือ ความเร็บในการวิ่งจะเพิ่มเป็น 200 กระโดด 150 สามารถเลือกโหมดได้ โหมด วิ่ง/กระโดด/วิ่ง+กระโดด",
        "grouptype": "เดินทาง",
        "getby": "ซื้อ Pass",
    },
    {
        "code": "FishShowcase",
        "nameTH": "บันทึกปลา",
        "icon": "/images/items/FishShowcase.png",
        "detail": "สมุดสำหรับดูข้อมูลปลาที่เราตกได้มาทั้งชีวิต",
        "grouptype": "ทั่วไป",
        "getby": "ไอเท็มเริ่มต้น",
    },
    {
        "code": "SniperGun",
        "nameTH": "ปืนGuลั่นปั้ง",
        "icon": "/images/items/SniperGun.png",
        "detail": "ปืนล็อคเป้า คนโดนจะติดสถานะ อัมพาต อ่านแชทไม่ได้ ใจเต้นแรง อ่านแชทไม่ได้ ขยับไม่ได้ ตัวเรืองแส ",
        "grouptype": "ไอเท็มซีซั่น (ห้ามใช้รังแกผู้อื่น)",
        "getby": "ร้านค้า Admin Boat",
    },
    {
        "code": "Scissors",
        "nameTH": "กรรไกรตัดผม",
        "icon": "/images/items/Scissors.png",
        "detail": "ใช้ตัดผมคนข้างหน้า หรือ ใช้สกิลเพื่อนโกนผมคนรอบข้าง",
        "grouptype": "แกล้ง",
        "getby": "ซื้อ Pass",
    },
    {
        "code": "Rope",
        "nameTH": "นังตัวดีมานี่",
        "icon": "/images/items/Rope.png",
        "detail": "ใช้จับผู้เล่นคนอื่นๆลากไปในที่ต่างๆได้ โดยไม่สามารถขัดขืน หรือหยิบของออกมาสู้ได้",
        "grouptype": "ไอเท็มซีซั่น (ห้ามใช้รังแกผู้อื่น)",
        "getby": "ร้านค้า Admin Boat",
    },
    {
        "code": "SharkBubbleGun",
        "nameTH": "ปืนฉลามฟองสบู่",
        "icon": "/images/items/SharkBubbleGun.png",
        "detail": "ปืนยิงฟองสบู่สีรุ้ง",
        "grouptype": "ทั่วไป",
        "getby": "ตกปลาสีรุ้ง",
    },
    {
        "code": "Godji",
        "nameTH": "ก็อตจิล่า",
        "icon": "/images/items/Godji.png",
        "detail": "ตุ๊กตาที่ใช้บ่งบอกความเป็นผู้เล่นยุคบุกเบิก",
        "grouptype": "ตุ๊กตา",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "CloudFly",
        "nameTH": "บินไปหา...",
        "icon": "/images/items/CloudFly.png",
        "detail": "อุปกรณ์ในการบินอย่างอิสระ",
        "grouptype": "เดินทาง",
        "getby": "ซื้อ Pass",
    },
    {
        "code": "LaserGun",
        "nameTH": "ปืนเลเซอร์",
        "icon": "/images/items/LaserGun.png",
        "detail": "ใช้เพื่อยิงให้ผู้อื่นตัวไหม้ดำ ชั่วคราว",
        "grouptype": "แกล้ง",
        "getby": "ตกปลาสีรุ้ง",
    },
    {
        "code": "BroomFly",
        "nameTH": "ไม้กวาดวิเศษ",
        "icon": "/images/items/BroomFly.png",
        "detail": "อุปกรณ์ในการบินอย่างอิสระ",
        "grouptype": "เดินทาง",
        "getby": "ซื้อ Pass",
    },
    {
        "code": "WingFly",
        "nameTH": "ปีกขาว",
        "icon": "/images/items/WingFly.png",
        "detail": "อุปกรณ์ในการบินอย่างอิสระ",
        "grouptype": "เดินทาง",
        "getby": "ซื้อ Pass",
    },
    {
        "code": "HelloKitty",
        "nameTH": "คิตตี้",
        "icon": "/images/items/HelloKitty.png",
        "detail": "ตุ๊กตาที่ใช้บ่งบอกความเป็นผู้เล่นยุคบุกเบิก",
        "grouptype": "ตุ๊กตา",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "Camera",
        "nameTH": "กล้อง",
        "icon": "/images/items/Camera.png",
        "detail": "ใช้ถ่ายรูปเพื่อหลอกขอไอจี",
        "grouptype": "ทั่วไป",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "BaseBallss3",
        "nameTH": "ฉันจะพาเธอลอย",
        "icon": "/images/items/BaseBallss3.png",
        "detail": "ใช้เพื่อฟาดผู้เล่นที่เรื้อน ออกไปสุดขอบฟ้า คลูดาวน์ 60 วินาที",
        "grouptype": "ไอเท็มซีซั่น (ห้ามใช้รังแกผู้อื่น)",
        "getby": "ร้านค้า Admin Boat",
    },
    {
        "code": "HalloweenRod",
        "nameTH": "เบ็ดฮัลโลวีน",
        "icon": "/images/items/HalloweenRod.png",
        "detail": "เบ็ดที่มีโชคอย่างมาก",
        "grouptype": "เบ็ด",
        "getby": "ตกปลาสีรุ้ง",
    },
    {
        "code": "LuckyHalloweenRod",
        "nameTH": "เบ็ดฮัลโลวีนพรีเมี่ยม",
        "icon": "/images/items/LuckyHalloweenRod.png",
        "detail": "เบ็ดที่มีโชคอย่างมากที่สุด",
        "grouptype": "เบ็ด",
        "getby": "ซื้อ Pass",
    },
    {
        "code": "PumkinHat",
        "nameTH": "หมวกฟักทอง[แฟชั่น]",
        "icon": "/images/items/PumkinHat.png",
        "detail": "หมวกฟักทองติดไฟ",
        "grouptype": "แฟชั่น",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "WitchHat",
        "nameTH": "หมวกแม่มด[แฟชั่น]",
        "icon": "/images/items/WitchHat.png",
        "detail": "หมวกแม่มดที่มีออร่า",
        "grouptype": "แฟชั่น",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "Kratong",
        "nameTH": "กระทง",
        "icon": "/images/items/Kratong.png",
        "detail": "ลอยกระทง",
        "grouptype": "ทั่วไป",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "KratongPass",
        "nameTH": "กระทงหลงเธอ",
        "icon": "/images/items/KratongPass.png",
        "detail": "ใช้ลอยกระทง พร้อมเขียนคำขอพรลงไป",
        "grouptype": "ทั่วไป",
        "getby": "ซื้อ Pass",
    },
    {
        "code": "Bunnydoll",
        "nameTH": "กระตุ่ยน้อย",
        "icon": "/images/items/Bunnydoll.png",
        "detail": "ตุ๊กตาที่ใช้บ่งบอกความเป็นผู้เล่นยุคบุกเบิก",
        "grouptype": "ตุ๊กตา",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "Skylantern",
        "nameTH": "โคมลอย",
        "icon": "/images/items/Skylantern.png",
        "detail": "ลอยโคมพร้อมเสียงเพลง",
        "grouptype": "ทั่วไป",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "HbdAdminBoatHat",
        "nameTH": "หมวกหมี",
        "icon": "/images/items/HbdAdminBoatHat.png",
        "detail": "หมวกหมีสุดน่ารัก ฉลองวันเกิดแอดมินโบ๊ท",
        "grouptype": "แฟชั่น",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "SelfieStick",
        "nameTH": "ไม้เซลฟี่",
        "icon": "/images/items/SelfieStick.png",
        "detail": "ใช้เซลฟี่ตัวเอง",
        "grouptype": "ทั่วไป",
        "getby": "ไอเท็มเริ่มต้น",
    },
    {
        "code": "RocketDance",
        "nameTH": "พลุหมุน",
        "icon": "/images/items/RocketDance.png",
        "detail": "พลุที่แสดงถึงความรัก",
        "grouptype": "ทั่วไป",
        "getby": "test",
    },
    {
        "code": "RocketRedblue",
        "nameTH": "พลุใหญ่",
        "icon": "/images/items/RocketRedblue.png",
        "detail": "พลุขนาดใหญ่",
        "grouptype": "ทั่วไป",
        "getby": "test",
    },
    {
        "code": "Rocketrandom",
        "nameTH": "พลุเล็ก",
        "icon": "/images/items/Rocketrandom.png",
        "detail": "พลุขนาดเล็ก",
        "grouptype": "ทั่วไป",
        "getby": "test",
    },
    {
        "code": "Textboard",
        "nameTH": "ป้ายข้อความ",
        "icon": "/images/items/Textboard.png",
        "detail": "ใช้เขียนข้อความ เพื่อถือป้าวยไว้",
        "grouptype": "ทั่วไป",
        "getby": "ตกปลาสีรุ้ง",
    },
    {
        "code": "WaterGun",
        "nameTH": "ปืนฉีดน้ำ",
        "icon": "/images/items/WaterGun.png",
        "detail": "ปืนที่พ่นน้ำออกมา",
        "grouptype": "ทั่วไป",
        "getby": "test",
    },
    {
        "code": "BananaPeel",
        "nameTH": "เปลือกกล้วย",
        "icon": "/images/items/BananaPeel.png",
        "detail": "วางกล้วย เพื่อให้ผู้อื่นมาเหยียบลื่นล้มหัวแตก",
        "grouptype": "แกล้ง",
        "getby": "ซื้อ Pass",
    },
    {
        "code": "HalloweenBalloonFly",
        "nameTH": "ลูกโป่งฮัลโลวีน",
        "icon": "/images/items/HalloweenBalloonFly.png",
        "detail": "อุปกรณ์ในการบินอย่างอิสระ",
        "grouptype": "เดินทาง",
        "getby": "ซื้อ Pass",
    },
    {
        "code": "BallTool",
        "nameTH": "อัญเชิญลูกบอล",
        "icon": "/images/items/BallTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้เป็นพาหนะ",
        "grouptype": "อัญเชิญ",
        "getby": "ซื้อ Pass",
    },
    {
        "code": "BmxTool",
        "nameTH": "อัญเชิญจักรยาน",
        "icon": "/images/items/BmxTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้เป็นพาหนะ",
        "grouptype": "อัญเชิญ",
        "getby": "ตกปลาสีรุ้ง",
    },
    {
        "code": "HalloweenMotorTool",
        "nameTH": "อัญเชิญมอไซค์ฮัลโลวีน",
        "icon": "/images/items/HalloweenMotorTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้เป็นพาหนะ",
        "grouptype": "อัญเชิญ",
        "getby": "ซื้อ Pass",
    },
    {
        "code": "BoatminiTool",
        "nameTH": "อัญเชิญเรือจิ๋ว",
        "icon": "/images/items/BoatminiTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้เป็นพาหนะ",
        "grouptype": "อัญเชิญ",
        "getby": "test",
    },
    {
        "code": "RedPlasticChairTool",
        "nameTH": "เก้าอี้มาลี",
        "icon": "/images/items/RedPlasticChairTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้ตกแต่งแมพ",
        "grouptype": "อัญเชิญ",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "ChairSpongeTool",
        "nameTH": "เก้าอี้SpongeBob",
        "icon": "/images/items/ChairSpongeTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้ตกแต่งแมพ",
        "grouptype": "อัญเชิญ",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "ChairMymelodyTool",
        "nameTH": "เก้าอี้Mymelody",
        "icon": "/images/items/ChairMymelodyTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้ตกแต่งแมพ",
        "grouptype": "อัญเชิญ",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "ChairRoyalTool",
        "nameTH": "เก้าอี้ราชา",
        "icon": "/images/items/ChairRoyalTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้ตกแต่งแมพ",
        "grouptype": "อัญเชิญ",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "ChairSwinglTool",
        "nameTH": "เก้าอี้สวิง",
        "icon": "/images/items/ChairSwinglTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้ตกแต่งแมพ",
        "grouptype": "อัญเชิญ",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "ChairGamingRGBTool",
        "nameTH": "เก้าอี้เกมมิ่งRGB",
        "icon": "/images/items/ChairGamingRGBTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้ตกแต่งแมพ",
        "grouptype": "อัญเชิญ",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "ChairTwoPersonTool",
        "nameTH": "เก้าอี้สองคน",
        "icon": "/images/items/ChairTwoPersonTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้ตกแต่งแมพ",
        "grouptype": "อัญเชิญ",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "ChairKuromiTool",
        "nameTH": "เก้าอี้Kuromi",
        "icon": "/images/items/ChairKuromiTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้ตกแต่งแมพ",
        "grouptype": "อัญเชิญ",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "ChairLoveWhiteTool",
        "nameTH": "เก้าอี้หัวใจขาว",
        "icon": "/images/items/ChairLoveWhiteTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้ตกแต่งแมพ",
        "grouptype": "อัญเชิญ",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "ChairDevilPremiumTool",
        "nameTH": "เก้าอี้ปีศาจ",
        "icon": "/images/items/ChairDevilPremiumTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้ตกแต่งแมพ",
        "grouptype": "อัญเชิญ",
        "getby": "ซื้อ Pass",
    },
    {
        "code": "ChairGroupThreeTool",
        "nameTH": "เก้าอี้กลุ่ม3",
        "icon": "/images/items/ChairGroupThreeTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้ตกแต่งแมพ",
        "grouptype": "อัญเชิญ",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "ChairPinkRabbitTool",
        "nameTH": "เก้าอี้เกมมิ่งกระต่ายชมพู",
        "icon": "/images/items/ChairPinkRabbitTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้ตกแต่งแมพ",
        "grouptype": "อัญเชิญ",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "ChairGamingBlueTool",
        "nameTH": "เก้าอี้เกมมิ่งฟ้า",
        "icon": "/images/items/ChairGamingBlueTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้ตกแต่งแมพ",
        "grouptype": "อัญเชิญ",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "ChairstrawberryTool",
        "nameTH": "เก้าอี้สตอร์เบอร์รี่",
        "icon": "/images/items/ChairstrawberryTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้ตกแต่งแมพ",
        "grouptype": "อัญเชิญ",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "ChairGamingBlackBlueTool",
        "nameTH": "เก้าอี้เกมมิ่งน้ำเงินดำ",
        "icon": "/images/items/ChairGamingBlackBlueTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้ตกแต่งแมพ",
        "grouptype": "อัญเชิญ",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "ChairSakuratreeswingTool",
        "nameTH": "เก้าอี้ซากุระชิงช้า",
        "icon": "/images/items/ChairSakuratreeswingTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้ตกแต่งแมพ",
        "grouptype": "อัญเชิญ",
        "getby": "ตกปลาสีรุ้ง",
    },
    {
        "code": "MotorWave110Tool",
        "nameTH": "อัญเชิญมอไซค์Wave110",
        "icon": "/images/items/MotorWave110Tool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้เป็นพาหนะ",
        "grouptype": "อัญเชิญ",
        "getby": "ตกปลาสีรุ้ง",
    },
    {
        "code": "MotorWave125iTool",
        "nameTH": "อัญเชิญมอไซค์Wave125i",
        "icon": "/images/items/MotorWave125iTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้เป็นพาหนะ",
        "grouptype": "อัญเชิญ",
        "getby": "ตกปลาสีรุ้ง",
    },
    {
        "code": "MotorWave125sTool",
        "nameTH": "อัญเชิญมอไซค์Wave125s",
        "icon": "/images/items/MotorWave125sTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้เป็นพาหนะ",
        "grouptype": "อัญเชิญ",
        "getby": "ตกปลาสีรุ้ง",
    },
    {
        "code": "MotorZoomerXTool",
        "nameTH": "อัญเชิญมอไซค์ZoomerX",
        "icon": "/images/items/MotorZoomerXTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้เป็นพาหนะ",
        "grouptype": "อัญเชิญ",
        "getby": "ตกปลาสีรุ้ง",
    },
    {
        "code": "NewsCamera",
        "nameTH": "กล้องนักข่าว",
        "icon": "/images/items/NewsCamera.png",
        "detail": "กล้องนักข่าว",
        "grouptype": "ทั่วไป",
        "getby": "ไอเท็มเริ่มต้น",
    },
    {
        "code": "NewsMic",
        "nameTH": "ไมค์นักข่าว",
        "icon": "/images/items/NewsMic.png",
        "detail": "ไมค์นักข่าว",
        "grouptype": "ทั่วไป",
        "getby": "ไอเท็มเริ่มต้น",
    },
    {
        "code": "CarskylabTool",
        "nameTH": "อัญเชิญมอไซค์รถตุ๊กๆ",
        "icon": "/images/items/CarskylabTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้เป็นพาหนะ",
        "grouptype": "อัญเชิญ",
        "getby": "test",
    },
    {
        "code": "FrozenHammer",
        "nameTH": "ค้อนแข็งโป๊ก",
        "icon": "/images/items/FrozenHammer.png",
        "detail": "ค้านไว้กำจัดเรื้อน ss4 เมื่อฟาดจะมีอนิเมชั่น + เอฟเฟค ทำให้ทุกคนรอบๆกลายเป็นน้ำแข็ง ",
        "grouptype": "ไอเท็มซีซั่น (ห้ามใช้รังแกผู้อื่น)",
        "getby": "ร้านค้า Admin Boat",
    },
    {
        "code": "Guitar",
        "nameTH": "กีต้าร์",
        "icon": "/images/items/Guitar.png",
        "detail": "กีต้าร์ที่สามารถ เลือกเลพงที่จะเล่นได้ เป็นเสียงแบบ Fingerstyle เพลงไทย",
        "grouptype": "ทั่วไป",
        "getby": "ซื้อ Pass",
    },
    {
        "code": "MotorHorseTool",
        "nameTH": "อัญเชิญม้า",
        "icon": "/images/items/MotorHorseTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้เป็นพาหนะ",
        "grouptype": "อัญเชิญ",
        "getby": "test",
    },
    {
        "code": "MotorDinoTool",
        "nameTH": "อัญเชิญไดโน",
        "icon": "/images/items/MotorDinoTool.png",
        "detail": "อัญเชิญออกมาเพื่อใช้เป็นพาหนะ",
        "grouptype": "อัญเชิญ",
        "getby": "test",
    },
    {
        "code": "Minion",
        "nameTH": "ตุ๊กตามินเนี่ยน",
        "icon": "/images/items/Minion.png",
        "detail": "ตุ๊กตาที่ใช้บ่งบอกความเป็นผู้เล่นยุคบุกเบิก",
        "grouptype": "ตุ๊กตา",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "WeddingBouquet",
        "nameTH": "ช่อดอกไม้แต่งงาน",
        "icon": "/images/items/WeddingBouquet.png",
        "detail": "เล่นอนิเมชั่นมอบดอกไม้พร้อมเพลงสุดน่ารัก",
        "grouptype": "ทั่วไป",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "HalloweenHammer",
        "nameTH": "ค้อนแรงโน้มถ่วง",
        "icon": "/images/items/HalloweenHammer.png",
        "detail": "เมื่อถือ จะเปลี่ยนแรงโน้มถ่วงของตัวเรา",
        "grouptype": "เดินทาง",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "RibbonRope",
        "nameTH": "โดนริบบิ้นอย่าดิ้นนะหนู",
        "icon": "/images/items/RibbonRope.png",
        "detail": "ใช้จับผู้เล่นคนอื่นๆลากไปในที่ต่างๆได้ โดยไม่สามารถขัดขืน หรือหยิบของออกมาสู้ได้",
        "grouptype": "ไอเท็มซีซั่น (ห้ามใช้รังแกผู้อื่น)",
        "getby": "ร้านค้า Admin Boat",
    },
    {
        "code": "Slapcolorflash",
        "nameTH": "ตบแสงสี",
        "icon": "/images/items/Slapcolorflash.png",
        "detail": "มือตบหน้าจอหลายสี+สกิลหน้าจอหลายสี คลูดาวน์ ตบ 1 นาที 20 วินาที สกิล  1 นาที 20 วินาที",
        "grouptype": "มือตบ",
        "getby": "test",
    },
    {
        "code": "Slapemoji_rain",
        "nameTH": "ตบอีโมจิ",
        "icon": "/images/items/Slapemoji_rain.png",
        "detail": "มือตบฝนอีโมจิ+สกิลฝนอีโมจิ คลูดาวน์ ตบ 1 นาที 20 วินาที สกิล  1 นาที 20 วินาที",
        "grouptype": "มือตบ",
        "getby": "test",
    },
    {
        "code": "Slapfastcut",
        "nameTH": "ตบมุมกล้อง",
        "icon": "/images/items/Slapfastcut.png",
        "detail": "มือตบภาพตัดไปมา+สกิลจอภาพตัดไปมา คลูดาวน์ ตบ 1 นาที 20 วินาที สกิล  1 นาที 20 วินาที",
        "grouptype": "มือตบ",
        "getby": "test",
    },
    {
        "code": "Slapfishbowl",
        "nameTH": "ตบยืดย่อ",
        "icon": "/images/items/Slapfishbowl.png",
        "detail": "มือตบซูมเข้าออก+สกิลจอซูมเข้าออก คลูดาวน์ ตบ 1 นาที 20 วินาที สกิล  1 นาที 20 วินาที",
        "grouptype": "มือตบ",
        "getby": "test",
    },
    {
        "code": "Slapslowmo",
        "nameTH": "ตบเซนเซอร์",
        "icon": "/images/items/Slapslowmo.png",
        "detail": "มือตบเซนเซอร์+สกิลจอเซนเซอร์ คลูดาวน์ ตบ 1 นาที 20 วินาที สกิล  1 นาที 20 วินาที",
        "grouptype": "มือตบ",
        "getby": "ซื้อ Pass",
    },
    {
        "code": "Slapwhirlwind",
        "nameTH": "ตบหมุนรอบตัว",
        "icon": "/images/items/Slapwhirlwind.png",
        "detail": "มือตบหัวหมุน+สกิลหมุนรอบตัว คลูดาวน์ ตบ 1 นาที 20 วินาที สกิล  1 นาที 20 วินาที",
        "grouptype": "มือตบ",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "SlipperSlap",
        "nameTH": "ขมับแม่ม",
        "icon": "/images/items/SlipperSlap.png",
        "detail": "ร้องเท้าใช้ตบคนให้หน้าทิ่ม",
        "grouptype": "มือตบ",
        "getby": "ตกปลาสีรุ้ง",
    },
    {
        "code": "FishTankMediumTool",
        "nameTH": "ตู้ปลาหรรษากลาง",
        "icon": "/images/items/FishTankMediumTool.png",
        "detail": "อัญเชิญ ตู้ปลาที่มาพร้อมรับป้องกันด้วยรหัสผ่าน ใส่คนได้จำนวนมาก",
        "grouptype": "อัญเชิญ",
        "getby": "ร้านค้า Admin Boat",
    },
    {
        "code": "FishTankSmallTool",
        "nameTH": "ตู้ปลาหรรษาเล็ก",
        "icon": "/images/items/FishTankSmallTool.png",
        "detail": "อัญเชิญ ตู้ปลาที่มาพร้อมรับป้องกันด้วยการนับจำนวนคน ใส่คนได้ 2 คน",
        "grouptype": "อัญเชิญ",
        "getby": "ตกปลาสีรุ้ง",
    },
    {
        "code": "FishTankMediumToolPass",
        "nameTH": "ตู้ปลาหรรษากลาง (pass)",
        "icon": "/images/items/FishTankMediumToolPass.png",
        "detail": "อัญเชิญ ตู้ปลาที่มาพร้อมรับป้องกันด้วยรหัสผ่าน ใส่คนได้จำนวนมาก",
        "grouptype": "อัญเชิญ",
        "getby": "ซื้อ Pass",
    },
    {
        "code": "FishTankSmallToolPass",
        "nameTH": "ตู้ปลาหรรษาเล็ก (pass)",
        "icon": "/images/items/FishTankSmallToolPass.png",
        "detail": "อัญเชิญ ตู้ปลาที่มาพร้อมรับป้องกันด้วยการนับจำนวนคน ใส่คนได้ 2 คน",
        "grouptype": "อัญเชิญ",
        "getby": "ซื้อ Pass",
    },
    {
        "code": "No1",
        "nameTH": "ดาราNo.1)",
        "icon": "/images/items/No1.png",
        "detail": "มงกุฏดาราอันดับ1 ไอเท็มจะเปลี่ยนผู้รับทุกเดือนตามลำดับ",
        "grouptype": "ดารา",
        "getby": "ติดTop1-3ดารา",
    },
    {
        "code": "No2",
        "nameTH": "ดาราNo.2)",
        "icon": "/images/items/No2.png",
        "detail": "มงกุฏดาราอันดับ2 ไอเท็มจะเปลี่ยนผู้รับทุกเดือนตามลำดับ",
        "grouptype": "ดารา",
        "getby": "ติดTop1-3ดารา",
    },
    {
        "code": "No3",
        "nameTH": "ดาราNo.3)",
        "icon": "/images/items/No3.png",
        "detail": "มงกุฏดาราอันดับ3 ไอเท็มจะเปลี่ยนผู้รับทุกเดือนตามลำดับ",
        "grouptype": "ดารา",
        "getby": "ติดTop1-3ดารา",
    },
    {
        "code": "PunchFight",
        "nameTH": "ต่อยแม่ม",
        "icon": "/images/items/PunchFight.png",
        "detail": "ไว้ให้เด็กที่ทะเลาะกันต่อยกัน",
        "grouptype": "แกล้ง",
        "getby": "test",
    },
    {
        "code": "SnowRod",
        "nameTH": "เบ็ดหิมะ",
        "icon": "/images/items/SnowRod.png",
        "detail": "เบ็ดตกปลาสายรีบ+โชค",
        "grouptype": "เบ็ด",
        "getby": "ซื้อ Pass",
    },
    {
        "code": "ChristmasRod",
        "nameTH": "เบ็ดคริสต์มาส",
        "icon": "/images/items/ChristmasRod.png",
        "detail": "เบ็ดตกปลาสายรีบ",
        "grouptype": "เบ็ด",
        "getby": "ตกปลาสีรุ้ง",
    },
    {
        "code": "CandyRod",
        "nameTH": "เบ็ดลูกอม",
        "icon": "/images/items/CandyRod.png",
        "detail": "เบ็ดตกปลาสายรีบ+เงิน",
        "grouptype": "เบ็ด",
        "getby": "ซื้อ Pass",
    },
    {
        "code": "ChistmasHat",
        "nameTH": "หมวกคริสต์มาส",
        "icon": "/images/items/ChistmasHat.png",
        "detail": "หมวกคริสต์มาสสุดน่ารัก",
        "grouptype": "แฟชั่น",
        "getby": "ร้านค้า Admin Note",
    },
    {
        "code": "SlipperSlapPass",
        "nameTH": "ร้องเท้าแตะแป๊ะที่หัว",
        "icon": "/images/items/SlipperSlapPass.png",
        "detail": "ร้องเท้าใช้ตบคนให้หน้าทิ่ม",
        "grouptype": "แกล้ง",
        "getby": "ซื้อ Pass",
    },
    {
        "code": "Megaphone",
        "nameTH": "แหกปากทั่วเซิร์ฟ",
        "icon": "/images/items/Megaphone.png",
        "detail": "ใช้ประกาศข้อความให้ทั้งเซิร์ฟเห็น",
        "grouptype": "ทั่วไป",
        "getby": "ไอเท็มเริ่มต้น",
    },
    {
        "code": "timesetting",
        "nameTH": "ท้องฟ้ายังเปลี่ยนสี",
        "icon": "/images/items/timesetting.png",
        "detail": "ใช้ปรับแต่งเวลา ท้องฟ้า และหมอก",
        "grouptype": "ทั่วไป",
        "getby": "ไอเท็มเริ่มต้น",
    },
    {
        "code": "TextAFKHat",
        "nameTH": "ป้ายAFK",
        "icon": "/images/items/TextAFKHat.png",
        "detail": "ป้ายคำพูด",
        "grouptype": "ทั่วไป",
        "getby": "ไอเท็มเริ่มต้น",
    },
    {
        "code": "TextShutHat",
        "nameTH": "ป้ายหุบปาก",
        "icon": "/images/items/TextShutHat.png",
        "detail": "ป้ายคำพูด",
        "grouptype": "ทั่วไป",
        "getby": "ไอเท็มเริ่มต้น",
    },
    {
        "code": "TextSingleHat",
        "nameTH": "ป้ายโสด",
        "icon": "/images/items/TextSingleHat.png",
        "detail": "ป้ายคำพูด",
        "grouptype": "ทั่วไป",
        "getby": "ไอเท็มเริ่มต้น",
    },
    {
        "code": "CustomSignTextTool",
        "nameTH": "ป้ายปักพื้น",
        "icon": "/images/items/CustomSignTextTool.png",
        "detail": "ป้ายสำหรับปักพื้นเขียนข้อความ",
        "grouptype": "อัญเชิญ",
        "getby": "test",
    },
    {
        "code": "LanternyellowTool",
        "nameTH": "โคมไฟเหลืองพกพา",
        "icon": "/images/items/LanternyellowTool.png",
        "detail": "วางเพื่อเพิ่มความสว่าง",
        "grouptype": "อัญเชิญ",
        "getby": "test",
    },
]
