export const PLACES = [
    {
        id: "harbor",
        name: "ท่าเรือ",
        description: "จุดเกิดท่าเรือ",
        x: 66,
        y: 73,
    },
    {
        id: "lighthouse",
        name: "ประภาคาร",
        description: "บ่อเป็ดเหลือง / เกมจริงหรือท้า / เรือเป็ด",
        x: 84,
        y: 88,
    },
    {
        id: "watherfall",
        name: "น้ำตก",
        description: "บ่อน้ำตกปลา / ถ้ำน้ำตก",
        x: 18,
        y: 72,
    },
    {
        id: "canival",
        name: "สวนสนุก",
        description: "โซนสวนสนุก / เครื่องเล่น",
        x: 45,
        y: 80,
    },
    {
        id: "village",
        name: "หมู่บ้านกลางแมพ",
        description: "หมู่บ้าน / บ่อน้ำพุ",
        x: 57,
        y: 54,
    },
    {
        id: "FishTank",
        name: "ตู้ปลา AFK",
        description: "ตกปลา แบบปลอดภัย ไร้คนรบกวน",
        x: 48,
        y: 31,
    },
    {
        id: "Camping",
        name: "จุดตั้งแคมป์",
        description: "ภูเขาตั้งแคมป์ นั่งชิวๆ ฟังเพลง ฮีลใจ ดูบรรยากาศ",
        x: 12,
        y: 39,
    },
    {
        id: "Pub",
        name: "ผับลับใต้ดิน",
        description: "ทางเข้ามีเห็ดสีสันสวยงาม / สังสรรค์ แดนซ์มันๆ เมากระจาย",
        x: 22,
        y: 26,
    },
    {
        id: "church",
        name: "บ้านผีสิงห์",
        description: "บ้านอลเวงชวนหลอน เข้าทางหน้าต่าง ประตูปิดตาย",
        x: 13,
        y: 13,
    },
    {
        id: "House",
        name: "บ้าน",
        description: "รวมกลุ่มกับเพื่อนๆ / ร้านเสื้อผ้า",
        x: 75,
        y: 17,
    },
    {
        id: "Shop",
        name: "ร้านขายไอเท็ม",
        description: "ร้านค้าแอดมิน / สะพานข้ามแม่น้ำ",
        x: 80,
        y: 38,
    },
    {
        id: "Boxing",
        name: "เวทีมวย",
        description: "การใช้กำลังไม่ใช่ทางออกที่ดีที่สุด แต่เร็วที่สุด",
        x: 88,
        y: 40,
    },
    {
        id: "xo",
        name: "ลานxo",
        description: "จุดนัดดวลไหวพริบ X O",
        x: 77,
        y: 48,
    },
    {
        id: "muan",
        name: "เสียงอีสานเวทีหมอรำ",
        description: "ม้วนหน้าฮ้าน / จุดเปลี่ยน เสื้อผ้า หน้า ผม",
        x: 92,
        y: 30,
    },
    {
        id: "Karaoke",
        name: "คาราโอเกะ",
        description: "มาร้องเกะกันเถอะ",
        x: 87,
        y: 57,
    },
    {
        id: "Beach",
        name: "ชายหาด",
        description: "จุดนั่งตกปลาชิวๆ",
        x: 85,
        y: 69,
    },
];