// วัตถุดิบฟาร์ม / ตั๋ว / กล่องกาชา / เงิน — ใช้ร่วมกันในหน้าโต๊ะคราฟ + กาชา
// วัตถุดิบพวกนี้ไม่มีรูป local (ในเกมเป็น rbxassetid) จึงใช้ emoji แทน
export const materialMeta = {
  Rice: { name: "ข้าว", emoji: "🌾" },
  RiceTop: { name: "ยอดข้าว", emoji: "🌾" },
  Iron: { name: "เหล็ก", emoji: "🔩" },
  Crowbar: { name: "เหล็กงัด", emoji: "🔧" },
  ChatTagCard: { name: "บัตรตั้งแท็กแชท", emoji: "🏷️" },
  Money: { name: "เงิน", emoji: "💰" },

  GoldenTicket: { name: "Golden Ticket", emoji: "🎫" },
  LuckyCraftTicket: { name: "Lucky Craft Ticket", emoji: "🍀" },
  GuaranteeCraftTicket: { name: "Guarantee Craft Ticket", emoji: "✅" },
  MarketBumpTicket: { name: "ตั๋วดันตลาด", emoji: "🚀" },
  FamilyCreateTicket: { name: "ตั๋วสร้างครอบครัว", emoji: "🏠" },
  FamilyExpandTicket: { name: "ตั๋วเพิ่มขนาดครอบครัว", emoji: "➕" },
  MarriageTicket: { name: "ตั๋วขอแต่งงาน", emoji: "💍" },

  OldClothes: { name: "เสื้อผ้าเก่า", emoji: "👕" },
  OldShoes: { name: "รองเท้าเก่า", emoji: "👟" },
  OldHat: { name: "หมวกเก่า", emoji: "🧢" },

  // บัตร EXP หมัด (มอนสเตอร์ฟาร์ม) + บัตรสกินเบ็ด
  MFExp100: { name: "บัตร EXP หมัด +100", emoji: "🃏" },
  MFExp500: { name: "บัตร EXP หมัด +500", emoji: "🃏" },
  MFExp1000: { name: "บัตร EXP หมัด +1000", emoji: "🎴" },
  MFExpX2: { name: "บัตร EXP หมัด x2", emoji: "✨" },
  RodSkinStartCard: { name: "บัตรการันตีตี +0", emoji: "🎴" },
  RodSkinSafeCard: { name: "บัตรกันตีบวกแตก", emoji: "🛡️" },

  // บัตรระบบขอพร (แอพขอพร)
  WishTicket: { name: "บัตรอธิษฐาน", emoji: "🙏" },
  WishCard: { name: "บัตรขอพร", emoji: "🎫" },
  HBDCard: { name: "บัตร Happy Birthday", emoji: "🎂" },

  // 🎂 บัตรจัดงานวันเกิด / 🚔 บัตรจับเข้าคุก — บัตรชนิด "กดใช้ได้เลยในกระเป๋า"
  BirthdayPartyCard: { name: "บัตรจัดงานวันเกิด", emoji: "🎂", icon: "/images/items/BirthdayPartyCard.png" },
  JailCard1: { name: "บัตรจับเข้าคุก 1 นาที", emoji: "🚔", icon: "/images/items/JailCard1.png" },
  JailCard3: { name: "บัตรจับเข้าคุก 3 นาที", emoji: "🚔", icon: "/images/items/JailCard3.png" },
  JailCard5: { name: "บัตรจับเข้าคุก 5 นาที", emoji: "🚔", icon: "/images/items/JailCard5.png" },
  JailCard10: { name: "บัตรจับเข้าคุก 10 นาที", emoji: "🚔", icon: "/images/items/JailCard10.png" },

  DollGachaBox: { name: "กล่องกาชาตุ๊กตา", emoji: "🎁" },
  ChairGachaBox: { name: "กล่องกาชาเก้าอี้", emoji: "🎁" },
  PetGachaBox: { name: "กล่องกาชาสัตว์เลี้ยง", emoji: "🎁" },
  SeasonGachaBox: { name: "กล่องกาชาซีซั่น", emoji: "🎁" },
  EventGachaBox: { name: "กล่องกาชา Event", emoji: "🎁" },
  AdminGachaBox: { name: "กล่องกาชา Admin", emoji: "🎁" },
  SadnoobBossGachaBox: { name: "กล่องกาชาบอส", emoji: "🎁" },
  DecorGachaBox: { name: "กาชาของตกแต่งv1", emoji: "🎉" },
  BubbleSkinGachaBox: { name: "กล่องกาชาฟองคำพูด", emoji: "🗨️", icon: "/images/items/BubbleSkinGachaBox.png" },
  HalloweenGachaBox: { name: "กล่องกาชาฮัลโลวีน", emoji: "🎃", icon: "/images/items/HalloweenGachaBox.png" },
  HWCrystalGachaBox: { name: "กล่องกาชาผลึกแร่", emoji: "💎", icon: "/images/items/HWCrystalGachaBox.png" },
  MineCrystal_Sugar: { name: "ผลึกลูกอมน้ำตาล", emoji: "💎", icon: "/images/items/MineCrystal_Sugar.png" },
  MineCrystal_Choco: { name: "ผลึกช็อกโกแลต", emoji: "💎", icon: "/images/items/MineCrystal_Choco.png" },
  MineCrystal_Caramel: { name: "ผลึกคาราเมล", emoji: "💎", icon: "/images/items/MineCrystal_Caramel.png" },
  MineCrystal_Straw: { name: "ผลึกสตรอว์เบอร์รี่", emoji: "💎", icon: "/images/items/MineCrystal_Straw.png" },
  MineCrystal_Mint: { name: "ผลึกมิ้นต์", emoji: "💎", icon: "/images/items/MineCrystal_Mint.png" },
  MineCrystal_Blue: { name: "ผลึกบลูเบอร์รี่", emoji: "💎", icon: "/images/items/MineCrystal_Blue.png" },
  MineCrystal_Matcha: { name: "ผลึกมัทฉะ", emoji: "💎", icon: "/images/items/MineCrystal_Matcha.png" },
  MineCrystal_Macaron: { name: "ผลึกมาการองพาสเทล", emoji: "💎", icon: "/images/items/MineCrystal_Macaron.png" },
  MineCrystal_Rainbow: { name: "ผลึกอมยิ้มสายรุ้ง", emoji: "💎", icon: "/images/items/MineCrystal_Rainbow.png" },
  MineCrystal_Diamond: { name: "ผลึกเพชรน้ำตาลกรวด", emoji: "💎", icon: "/images/items/MineCrystal_Diamond.png" },
  MineBar_Sugar: { name: "แท่งลูกอมน้ำตาล", emoji: "🧱" },
  MineBar_Choco: { name: "แท่งช็อกโกแลต", emoji: "🧱" },
  MineBar_Caramel: { name: "แท่งคาราเมล", emoji: "🧱" },
  MineBar_Straw: { name: "แท่งสตรอว์เบอร์รี่", emoji: "🧱" },
  MineBar_Mint: { name: "แท่งมิ้นต์", emoji: "🧱" },
  MineBar_Blue: { name: "แท่งบลูเบอร์รี่", emoji: "🧱" },
  MineBar_Matcha: { name: "แท่งมัทฉะ", emoji: "🧱" },
  MineBar_Macaron: { name: "แท่งมาการองพาสเทล", emoji: "🧱" },
  MineBar_Rainbow: { name: "แท่งอมยิ้มสายรุ้ง", emoji: "🧱" },
  MineBar_Diamond: { name: "แท่งเพชรน้ำตาลกรวด", emoji: "🧱" },
};
