// สัตว์เลี้ยง (PetConfig) — เรียงตาม Order ในเกม
// buff สเกลตามเลเวล (Lv.1 → Lv.50) • ดึง + verify กับเกมจริง 2026-07-12
export const petall = [
  {
    key: "Bunny",
    displayName: "กระต่าย",
    emoji: "🐰",
    rarity: "Common",
    food: { item: "Rice", display: "ต้นข้าว" },
    gachaWeight: 100,
    ability: "ดรอปข้าวฟรีทุก 20 นาที",
    abilityLv1: "ดรอปข้าว 5%/20นาที (1 ชิ้น)",
    abilityLv50: "ดรอปข้าว 29.5%/20นาที (1 ชิ้น)",
    obtain: "🛠️ คราฟที่โต๊ะคราฟ (ติด 15%)",
  },
  {
    key: "SharkPet",
    displayName: "ฉลาม",
    emoji: "🦈",
    rarity: "Uncommon",
    food: { item: "Rice", display: "ต้นข้าว" },
    gachaWeight: 100,
    ability: "ตีบอสโลกแรงขึ้น",
    abilityLv1: "ตีบอสโลก +1 ดาเมจ/คลิก",
    abilityLv50: "ตีบอสโลก +50 ดาเมจ/คลิก",
    obtain: "☠️ ดรอปจากบอสมอนสเตอร์มหากาฬ (1%/รอบ)",
  },
  {
    key: "Dog",
    displayName: "หมา",
    emoji: "🐶",
    rarity: "Uncommon",
    food: { item: "Rice", display: "ต้นข้าว" },
    gachaWeight: 100,
    ability: "ขุดเงินให้ทุก 20 นาที",
    abilityLv1: "ได้เงิน 500/20นาที",
    abilityLv50: "ได้เงิน 1,725/20นาที",
    obtain: "🧟 ดรอปจากบอสซอมบี้ยักษ์ (1%/รอบ)",
  },
  {
    key: "frog",
    displayName: "กบ",
    emoji: "🐸",
    rarity: "Rare",
    food: { item: "Rice", display: "ต้นข้าว" },
    gachaWeight: 100,
    ability: "เพิ่มโอกาสตกปลาสีรุ้ง",
    abilityLv1: "โอกาสปลาสีรุ้ง +1%",
    abilityLv50: "โอกาสปลาสีรุ้ง +50%",
    obtain: "🎣 ดรอปตอนตกปลา (1%/ครั้ง)",
  },
  {
    key: "Chicken",
    displayName: "ไก่",
    emoji: "🐔",
    rarity: "Rare",
    food: { item: "Rice", display: "ต้นข้าว" },
    gachaWeight: 100,
    ability: "เพิ่มยอดข้าวตอนเกี่ยวข้าว",
    abilityLv1: "โอกาสยอดข้าว +1.5%",
    abilityLv50: "โอกาสยอดข้าว +75%",
    obtain: "🌾 ดรอปตอนเกี่ยวข้าว (2%/ครั้ง)",
  },
  {
    key: "Cat",
    displayName: "แมว",
    emoji: "🐱",
    rarity: "Epic",
    food: { item: "Rice", display: "ต้นข้าว" },
    gachaWeight: 100,
    ability: "เพิ่มโชคเปิดกาชา",
    abilityLv1: "โชคกาชา (ของหายาก) +0.5%",
    abilityLv50: "โชคกาชา (ของหายาก) +25%",
    obtain: "🎰 ดรอปตอนเปิดกาชา (1%/กล่อง)",
  },
  {
    key: "DarkDevil",
    displayName: "ดาร์คเดวิล",
    emoji: "😈",
    rarity: "Legendary",
    food: { item: "RiceTop", display: "ยอดข้าว" },
    gachaWeight: 20,
    ability: "ตำนาน: บัฟหลายอย่างพร้อมกัน",
    abilityLv1: "ตีบอส +2 • เงิน 1,000/20น • โชคกาชา +1% • ปลาสีรุ้ง +1%",
    abilityLv50: "ตีบอส +100 • เงิน 3,450/20น • โชคกาชา +50% • ปลาสีรุ้ง +50%",
    obtain: "🎰 กาชาสัตว์เลี้ยง (30M/กล่อง)",
  },
  {
    key: "404Demon",
    displayName: "404 เดมอน",
    emoji: "👹",
    rarity: "Legendary",
    food: { item: "RiceTop", display: "ยอดข้าว" },
    gachaWeight: 5,
    robux: 4999,
    ability: "ตำนาน: ตีบอส + โชคปลา + เงินตกปลา + แฮคแอร์ดรอป",
    abilityLv1: "ตีบอส +1 • โชคปลารุ้ง +1% • เงินตกปลา +0.1% • แฮคแอร์ดรอป 1/ลูก",
    abilityLv50: "ตีบอส +50 • โชคปลารุ้ง +50% • เงินตกปลา +5% • แฮคแอร์ดรอป 6/ลูก",
    obtain: "🎰 กาชาสัตว์เลี้ยง หรือ 🛒 ซื้อ/กิ๊ฟ 4,999 Robux",
  },
  {
    key: "Haxigator",
    displayName: "แฮคเกอร์",
    emoji: "👾",
    rarity: "Event",
    food: { item: "Iron", display: "เหล็ก" },
    gachaWeight: 0, // ไม่อยู่ในกาชา
    robux: 799,
    ability: "อีเวนต์: โชคปลา + เงินตกปลา + แฮคแอร์ดรอป",
    abilityLv1: "โชคปลารุ้ง +0.5% • เงินตกปลา +0.04% • แฮคแอร์ดรอป 1/ลูก",
    abilityLv50: "โชคปลารุ้ง +25% • เงินตกปลา +2% • แฮคแอร์ดรอป 3/ลูก",
    obtain: "🛒 ซื้อ/กิ๊ฟ 799 Robux • หรือการันตีเลือกในวงล้อ/เชิญเพื่อน",
  },
];

export const petByKey = Object.fromEntries(petall.map((p) => [p.key, p]));

export const petMeta = {
  maxLevel: 50,
  maxEquip: 5,
  gachaPrice: 30000000,
  expPerFood: 5,
  expPerLevel: 100,
  foodPerLevel: 20, // 100 exp / 5 ต่ออาหาร
  foodToMax: 980, // (50-1) × 20
  foodItem: "Rice",
  foodDisplay: "ต้นข้าว",
  dupRefundItem: "Rice",
  dupRefundAmount: 100,
};
