// ร้านค้า NPC (ShopConfig) — ซื้อด้วยเงินในเกม (ไม่ใช่ Robux)
// รูปแบบ: [code, displayName, price, minLevel, limited?]
// limited = true คือของ Limited/ตามเทศกาล (มีช่วงเวลาขาย)

export const shopVendors = [
  {
    key: "limited",
    title: "ร้านค้า Limited",
    emoji: "💎",
    note: "อาวุธซีซั่น (SS) หายาก มีจำนวนจำกัดและขายเป็นช่วงเวลา",
    items: [
      ["SniperGun", "SS1 ปืนล็อคเป้า", 3800000, 50, true],
      ["Rope", "SS2 นังตัวดีมานี่", 2800000, 50, true],
      ["BaseBallss3", "SS3 ฉันจะพาเธอลอย", 2400000, 50, true],
      ["FrozenHammer", "SS4 หนาวนี้กอดใคร", 2800000, 50, true],
      ["RibbonRope", "SS5 โดนริบบิ้นอย่าดิ้นนะหนู", 3200000, 50, true],
      ["Sniperinvite", "SS6 สไนเปอร์อัญเชิญ", 5500000, 50, true],
      ["FishTankMediumTool", "ตู้หรรษาระดับกลาง", 9999999, 6, false],
    ],
  },
  {
    key: "general",
    title: "ร้านค้าของทั่วไป",
    emoji: "🛍️",
    note: "เก้าอี้ ตุ๊กตา หมวก และของตกแต่งทั่วไป",
    items: [
      ["Camera", "กล้อง", 99999, 50, false],
      ["Godji", "ก็อตจิล่า", 999, 100, false],
      ["Minion", "มินเนี่ยน", 0, 6, false],
      ["Bunnydoll", "กระตุ่ยน้อย", 0, 6, false],
      ["KittyLove", "ตุ๊กตา KittyLove", 0, 6, false],
      ["HelloKitty", "คิดตี้", 25000, 6, false],
      ["mymelody_Beta", "มายเมโลดี้", 25000, 6, false],
      ["kuromi_Beta", "คุโรมิ", 25000, 6, false],
      ["WeddingBouquet", "ช่อดอกไม้แต่งงาน", 50000, 6, false],
      ["Slapwhirlwind", "ตบหมุนรอบตัว", 555555, 6, false],
      ["Umbrellagravity", "ร่มแรงโน้มถ่วง", 50000, 6, false],
      ["RedPlasticChairTool", "เก้าอี้มาลี", 10000, 6, false],
      ["ChairSpongeTool", "เก้าอี้ SpongeBob", 15000, 6, false],
      ["ChairstrawberryTool", "เก้าอี้สตรอว์เบอร์รี", 20000, 6, false],
      ["ChairLoveWhiteTool", "เก้าอี้หัวใจขาว", 20000, 6, false],
      ["ChairGamingBlueTool", "เก้าอี้เกมมิ่งฟ้า", 35000, 6, false],
      ["ChairMymelodyTool", "เก้าอี้ Mymelody", 50000, 6, false],
      ["ChairRoyalTool", "เก้าอี้ราชา", 50000, 6, false],
      ["ChairKuromiTool", "เก้าอี้ Kuromi", 50000, 6, false],
      ["ChairPinkRabbitTool", "เก้าอี้กระต่ายชมพู", 50000, 6, false],
      ["ChairGamingBlackBlueTool", "เก้าอี้เกมมิ่งน้ำเงินดำ", 50000, 6, false],
      ["ChairTwoPersonTool", "เก้าอี้สองคน", 120000, 6, false],
      ["ChairSwinglTool", "เก้าอี้สวิง", 150000, 6, false],
      ["ChairGroupThreeTool", "เก้าอี้กลุ่ม 3", 180000, 6, false],
      ["ChairGamingRGBTool", "เก้าอี้เกมมิ่ง RGB", 500000, 6, false],
      ["PumkinHat", "หมวกฟักทอง [แฟชั่น]", 99999, 20, true],
      ["WitchHat", "หมวกแม่มด [แฟชั่น]", 15000, 6, true],
      ["Kratong", "กระทง", 9999, 6, true],
      ["Skylantern", "โคมลอย", 9999, 6, true],
      ["ChistmasHat", "หมวกคริสต์มาส", 0, 6, true],
      ["HalloweenHammer", "ค้อนแรงโน้มถ่วง", 0, 6, true],
      ["Rocketrandom", "พลุปีใหม่", 0, 6, true],
      ["HbdAdminBoatHat", "หมวกหมี HBD Admin Boat", 1234, 6, true],
    ],
  },
];
