export const shoeprofile = [
    {
        ocname: "Boat",
        icname: "Blackpoi5",
        icid: "Blackpoi5",
        caption: "แก้วเป็นของแข็ง เบียร์เป็นของเหลว ส่วนหัวใจเป้นได้แค่ของเล่น",
        icimage: "/images/showprofile/icBlackpoi5.png",
        ocimage: "/images/showprofile/ocBlackpoi5.png",
        facebookurl: "",
        instagramurl: "https://www.instagram.com/boatms",
        tiktokurl: "https://www.tiktok.com/@boatmousay",
        donate: "Admin",
    },
    {
        ocname: "แบมแบม",
        icname: "แบมแบม",
        icid: "bamab1911",
        caption: "นี่ไม่ใช่ตัวเลือก นี่ตัวซีเคร็ท",
        icimage: "/images/showprofile/icbamab1911.png",
        ocimage: "/images/showprofile/ocbamab1911.png",
        facebookurl: "",
        instagramurl: "https://www.instagram.com/bbbamabb?igsh=NzN6OHZpNHpmZmRt",
        tiktokurl: "https://www.tiktok.com/@bbamabbb?_r=1&_t=ZS-91TGTCZpvec",
        donate: "500000",
    },
    {
        ocname: "สายป่าน",
        icname: "kuyhom",
        icid: "kuyhom",
        caption: "เจ๊กล้วยหอมซีเคร็ท",
        icimage: "/images/showprofile/ickuyhom.png",
        ocimage: "/images/showprofile/ockuyhom.png",
        facebookurl: "",
        instagramurl: "",
        tiktokurl: "",
        donate: "50000",
    },
    {
        ocname: "ชมพู่",
        icname: "ชมพู่",
        icid: "chom_25511",
        caption: "นอนทั้งวัน",
        icimage: "/images/showprofile/icchom_25511.png",
        ocimage: "/images/showprofile/occhom_25511.png",
        facebookurl: "",
        instagramurl: "https://www.instagram.com/c_chompoo_51/",
        tiktokurl: "",
        donate: "50000",
    },
    {
        ocname: "ต้า",
        icname: "ตาต้า",
        icid: "Ta_255007",
        caption: "ตาต้าเด็กดีสุดในแมพ",
        icimage: "/images/showprofile/icTa_255007.png",
        ocimage: "/images/showprofile/ocTa_255007.png",
        facebookurl: "https://www.facebook.com/sareeta.khianhin.9",
        instagramurl: "https://www.instagram.com/sareeta_taaaaaa?igsh=MXZlYnJ6aXZ0cHYwbg%3D%3D&utm_source=qr",
        tiktokurl: "https://www.tiktok.com/@sareeta_2550?_r=1&_t=ZS-91TSbcKmhsG",
        donate: "1000000",
    },
    {
        ocname: "",
        icname: "",
        icid: "",
        caption: "",
        icimage: "",
        ocimage: "",
        facebookurl: "",
        instagramurl: "",
        tiktokurl: "",
        donate: "300",
    },
    {
        ocname: "",
        icname: "",
        icid: "",
        caption: "",
        icimage: "",
        ocimage: "",
        facebookurl: "",
        instagramurl: "",
        tiktokurl: "",
        donate: "400",
    }, 
]