export const shoeprofile = [
    {
        ocname: "Boat",
        icname: "Blackpoi5",
        icid: "Blackpoi5",
        caption: "แก้วเป็นของแข็ง เบียร์เป็นของเหลว ส่วนหัวใจเป้นได้แค่ของเล่น",
        icimage: "/images/showprofile/icBlackpoi5.png",
        ocimage: "/images/showprofile/ocBlackpoi5.png",
        facebookurl: "",
        instagramurl: "https://www.instagram.com/boatms",
        tiktokurl: "https://www.tiktok.com/@boatmousay",
        donate: "Admin",
    },
    {
        ocname: "แบมแบม",
        icname: "แบมแบม",
        icid: "bamab1911",
        caption: "นี่ไม่ใช่ตัวเลือก นี่ตัวซีเคร็ท",
        icimage: "/images/showprofile/icbamab1911.png",
        ocimage: "/images/showprofile/ocbamab1911.png",
        facebookurl: "",
        instagramurl: "https://www.instagram.com/bbbamabb?igsh=NzN6OHZpNHpmZmRt",
        tiktokurl: "https://www.tiktok.com/@bbamabbb?_r=1&_t=ZS-91TGTCZpvec",
        donate: "800000",
    },
    {
        ocname: "สายป่าน",
        icname: "kuyhom",
        icid: "kuyhom",
        caption: "เจ๊กล้วยหอมซีเคร็ท",
        icimage: "/images/showprofile/ickuyhom.png",
        ocimage: "/images/showprofile/ockuyhom.png",
        facebookurl: "",
        instagramurl: "",
        tiktokurl: "",
        donate: "150000",
    },
    {
        ocname: "ชมพู่",
        icname: "ชมพู่",
        icid: "chom_25511",
        caption: "นอนทั้งวัน",
        icimage: "/images/showprofile/icchom_25511.png",
        ocimage: "/images/showprofile/occhom_25511.png",
        facebookurl: "",
        instagramurl: "https://www.instagram.com/c_chompoo_51/",
        tiktokurl: "",
        donate: "50000",
    },
    {
        ocname: "ต้า",
        icname: "ตาต้า",
        icid: "Ta_255007",
        caption: "ตาต้าเด็กดีสุดในแมพ",
        icimage: "/images/showprofile/icTa_255007.png",
        ocimage: "/images/showprofile/ocTa_255007.png",
        facebookurl: "https://www.facebook.com/sareeta.khianhin.9",
        instagramurl: "https://www.instagram.com/sareeta_taaaaaa?igsh=MXZlYnJ6aXZ0cHYwbg%3D%3D&utm_source=qr",
        tiktokurl: "https://www.tiktok.com/@sareeta_2550?_r=1&_t=ZS-91TSbcKmhsG",
        donate: "1750000",
    },
    {
        ocname: "เตยหอม",
        icname: "เตยหอม",
        icid: "toeyhom72",
        caption: "แคปชั่นไม่รู้ แคปหมูแน่นอน",
        icimage: "/images/showprofile/ictoeyhom72.png",
        ocimage: "/images/showprofile/octoeyhom72.png",
        facebookurl: "",
        instagramurl: "https://www.instagram.com/tt_eerarat?igsh=MWF2bzRkYTd3czZ1aA%3D%3D&utm_source=qr",
        tiktokurl: "",
        donate: "300000",
    },
    {
        ocname: "บอส",
        icname: "Potato",
        icid: "iAm_BossEiEi",
        caption: "พิราบ เขา แมวขาว มันฝรั่ง เขี้ยวกุด",
        icimage: "/images/showprofile/iciAm_BossEiEi.png",
        ocimage: "/images/showprofile/ociAm_BossEiEi.png",
        facebookurl: "",
        instagramurl: "",
        tiktokurl: "",
        donate: "160000",
    },
    {
        ocname: "ชมพู",
        icname: "กะเปี๊ยก",
        icid: "Puji_Saka",
        caption: "รอแฟนเค้าหลับเดี๋ยวโทรกลับนะ",
        icimage: "/images/showprofile/icPuji_Saka.png",
        ocimage: "/images/showprofile/ocPuji_Saka.png",
        facebookurl: "https://www.facebook.com/share/1KcY6znzuv/?mibextid=wwXIfr",
        instagramurl: "https://www.instagram.com/qitsucxh",
        tiktokurl: "",
        donate: "1320000",
    },
    {
        ocname: "หมูหวาน หรือ หวาน",
        icname: "Khaiharn",
        icid: "aa0805985782",
        caption: "หมูเน่า แต่ไม่เน่าอาบน้ำแล้ว",
        icimage: "/images/showprofile/icKhaiharn.png",
        ocimage: "/images/showprofile/ocKhaiharn.png",
        facebookurl: "",
        instagramurl: "https://www.instagram.com/hmu__2008",
        tiktokurl: "https://www.tiktok.com/@moowan17_2008",
        donate: "50000",
    },
    {
        ocname: "แอมแปร์",
        icname: "ทูน่า",
        icid: "Tuna_lmm",
        caption: "อะปะละหึอุติมุจะม่ะติหึๆ",
        icimage: "/images/showprofile/icTuna_lmm.png",
        ocimage: "/images/showprofile/ocTuna_lmm.png",
        facebookurl: "",
        instagramurl: " https://www.instagram.com/i.iluminelle",
        tiktokurl: "",
        donate: "2030000",
    },
    {
        ocname: "เบส 「　ベース　」",
        icname: "เบส",
        icid: "bestiiz1235",
        caption: "ทำอะไรก็ได้ขอเป็นคนดีก็พอ",
        icimage: "/images/showprofile/icbestiiz1235.png",
        ocimage: "/images/showprofile/ocbestiiz1235.png",
        facebookurl: "",
        instagramurl: "https://www.instagram.com/gojira_bro",
        tiktokurl: "",
        donate: "350000",
    },
    // {
    //     ocname: "",
    //     icname: "",
    //     icid: "",
    //     caption: "",
    //     icimage: "",
    //     ocimage: "",
    //     facebookurl: "",
    //     instagramurl: "",
    //     tiktokurl: "",
    //     donate: "0",
    // },
]