// ท่าเต้น/อีโมทที่หน้าสตรีมเมอร์เลือกได้ — ชื่อต้องตรงกับ Config.EMOTES ในเกม (ReplicatedStorage.Config)
// StreamerServer หา id จากชื่อ · อัปเดตเมื่อเพิ่ม/ลบท่าในเกม (ล่าสุด 21/09/2026: 200 ท่า)
export const streamerEmotes = [{"name":"e_Fishing03","label":"Fishing03","cat":"emote"},
{"name":"p_Sit 1","label":"Sit 1","cat":"pose"},
{"name":"p_Sit 2","label":"Sit 2","cat":"pose"},
{"name":"p_Sit 3","label":"Sit 3","cat":"pose"},
{"name":"p_sleep","label":"sleep","cat":"pose"},
{"name":"p_Sleep Lie","label":"Sleep Lie","cat":"pose"},
{"name":"e_Click","label":"Click","cat":"emote"},
{"name":"d_Automatic Save","label":"Automatic Save","cat":"dance"},
{"name":"d_Boneless","label":"Boneless","cat":"dance"},
{"name":"d_Boogie Bomb","label":"Boogie Bomb","cat":"dance"},
{"name":"d_Breakdown","label":"Breakdown","cat":"dance"},
{"name":"d_Calamity","label":"Calamity","cat":"dance"},
{"name":"d_Crackdown","label":"Crackdown","cat":"dance"},
{"name":"d_Crazy Feet","label":"Crazy Feet","cat":"dance"},
{"name":"e_Dab","label":"Dab","cat":"emote"},
{"name":"d_Default Dance","label":"Default Dance","cat":"dance"},
{"name":"e_Eagle","label":"Eagle","cat":"emote"},
{"name":"d_Electro Shuffle","label":"Electro Shuffle","cat":"dance"},
{"name":"d_Electro Shuffle 2","label":"Electro Shuffle 2","cat":"dance"},
{"name":"d_Electro Swing","label":"Electro Swing","cat":"dance"},
{"name":"d_Fancy Feet","label":"Fancy Feet","cat":"dance"},
{"name":"d_Flapper","label":"Flapper","cat":"dance"},
{"name":"e_Flippin Incredible","label":"Flippin Incredible","cat":"emote"},
{"name":"d_Floss","label":"Floss","cat":"dance"},
{"name":"d_Free Flow","label":"Free Flow","cat":"dance"},
{"name":"d_Fresh","label":"Fresh","cat":"dance"},
{"name":"e_Guitar","label":"Guitar","cat":"emote"},
{"name":"e_HeadBanger","label":"HeadBanger","cat":"emote"},
{"name":"e_Hot Marat","label":"Hot Marat","cat":"emote"},
{"name":"d_Hotline Bling","label":"Hotline Bling","cat":"dance"},
{"name":"d_Hype","label":"Hype","cat":"dance"},
{"name":"d_Inf Dab","label":"Inf Dab","cat":"dance"},
{"name":"d_Kazotsky Kick","label":"Kazotsky Kick","cat":"dance"},
{"name":"d_Orange Justice","label":"Orange Justice","cat":"dance"},
{"name":"d_Pop Lock","label":"Pop Lock","cat":"dance"},
{"name":"d_Pumpernickel","label":"Pumpernickel","cat":"dance"},
{"name":"d_Ride The Pony","label":"Ride The Pony","cat":"dance"},
{"name":"e_Running Man","label":"Running Man","cat":"emote"},
{"name":"e_Showstopper","label":"Showstopper","cat":"emote"},
{"name":"d_Smooth Moves","label":"Smooth Moves","cat":"dance"},
{"name":"d_Sprinkler","label":"Sprinkler","cat":"dance"},
{"name":"d_Take The L","label":"Take The L","cat":"dance"},
{"name":"d_The Robot","label":"The Robot","cat":"dance"},
{"name":"d_Twist","label":"Twist","cat":"dance"},
{"name":"d_Worm","label":"Worm","cat":"dance"},
{"name":"d_Yeet","label":"Yeet","cat":"dance"},
{"name":"d_Zany","label":"Zany","cat":"dance"},
{"name":"e_jubilation","label":"jubilation","cat":"emote"},
{"name":"p_Matching Right Heart","label":"Matching Right Heart","cat":"pose"},
{"name":"p_Head pet sit","label":"Head pet sit","cat":"pose"},
{"name":"e_Bear Hug","label":"Bear Hug","cat":"emote"},
{"name":"p_Face down Sleep","label":"Face down Sleep","cat":"pose"},
{"name":"p_On beach Sleep","label":"On beach Sleep","cat":"pose"},
{"name":"p_Cute sit sway","label":"Cute sit sway","cat":"pose"},
{"name":"p_On cloud Sleep","label":"On cloud Sleep","cat":"pose"},
{"name":"e_Boxing","label":"Boxing","cat":"emote"},
{"name":"p_On floor Sleep","label":"On floor Sleep","cat":"pose"},
{"name":"p_Sideway Sleep","label":"Sideway Sleep","cat":"pose"},
{"name":"p_Silly Sleep","label":"Silly Sleep","cat":"pose"},
{"name":"p_Stand Sleep","label":"Stand Sleep","cat":"pose"},
{"name":"e_Side Hug","label":"Side Hug","cat":"emote"},
{"name":"p_Nonchalant","label":"Nonchalant","cat":"pose"},
{"name":"p_Aura Pose","label":"Aura Pose","cat":"pose"},
{"name":"p_Kneeling Gift","label":"Kneeling Gift","cat":"pose"},
{"name":"e_AuraSit","label":"AuraSit","cat":"emote"},
{"name":"p_Shy Pose","label":"Shy Pose","cat":"pose"},
{"name":"p_Wall lean Pose","label":"Wall lean Pose","cat":"pose"},
{"name":"e_Beggin","label":"Beggin","cat":"emote"},
{"name":"p_Beauty Sleep","label":"Beauty Sleep","cat":"pose"},
{"name":"p_Cute idle Pose 3","label":"Cute idle Pose 3","cat":"pose"},
{"name":"p_Matching Left Heart","label":"Matching Left Heart","cat":"pose"},
{"name":"p_SquatSit","label":"SquatSit","cat":"pose"},
{"name":"p_Float Sleep","label":"Float Sleep","cat":"pose"},
{"name":"p_ThinkingSit","label":"ThinkingSit","cat":"pose"},
{"name":"p_Menace Pose","label":"Menace Pose","cat":"pose"},
{"name":"p_CrossSit","label":"CrossSit","cat":"pose"},
{"name":"p_Cute Shy Pose","label":"Cute Shy Pose","cat":"pose"},
{"name":"p_Kawaii Pose","label":"Kawaii Pose","cat":"pose"},
{"name":"p_LeanSIt","label":"LeanSIt","cat":"pose"},
{"name":"p_Head pet","label":"Head pet","cat":"pose"},
{"name":"e_Spin Around","label":"Spin Around","cat":"emote"},
{"name":"p_Cute idle Pose 2","label":"Cute idle Pose 2","cat":"pose"},
{"name":"p_Cute Kawaii Sit","label":"Cute Kawaii Sit","cat":"pose"},
{"name":"p_Baby Sit","label":"Baby Sit","cat":"pose"},
{"name":"p_Normal Sleep","label":"Normal Sleep","cat":"pose"},
{"name":"p_Chest hug Pose","label":"Chest hug Pose","cat":"pose"},
{"name":"p_Cute idle Pose","label":"Cute idle Pose","cat":"pose"},
{"name":"p_PartySit","label":"PartySit","cat":"pose"},
{"name":"d_Bully Maguire","label":"Bully Maguire","cat":"dance"},
{"name":"d_Ashi Ashi Dance","label":"Ashi Ashi Dance","cat":"dance"},
{"name":"d_Beautiful Dance","label":"Beautiful Dance","cat":"dance"},
{"name":"d_Floss Dance","label":"Floss Dance","cat":"dance"},
{"name":"d_Get em","label":"Get em","cat":"dance"},
{"name":"d_Wait..They","label":"Wait..They","cat":"dance"},
{"name":"d_Olivia Rodrigo Head Bop","label":"Olivia Rodrigo Head Bop","cat":"dance"},
{"name":"d_Head Banger","label":"Head Banger","cat":"dance"},
{"name":"d_Never Gonna give you up","label":"Never Gonna give you up","cat":"dance"},
{"name":"d_Trip Out","label":"Trip Out","cat":"dance"},
{"name":"d_Make You Mine","label":"Make You Mine","cat":"dance"},
{"name":"d_Rock out","label":"Rock out","cat":"dance"},
{"name":"d_SpongeBob Dance","label":"SpongeBob Dance","cat":"dance"},
{"name":"d_Tell Me, Tell Me!3","label":"Tell Me, Tell Me!3","cat":"dance"},
{"name":"d_Shake it in Circle","label":"Shake it in Circle","cat":"dance"},
{"name":"d_Baddie Belly Dance","label":"Baddie Belly Dance","cat":"dance"},
{"name":"e_Caramelldansen","label":"Caramelldansen","cat":"emote"},
{"name":"d_Die Lit","label":"Die Lit","cat":"dance"},
{"name":"d_Arona Dance Meme","label":"Arona Dance Meme","cat":"dance"},
{"name":"d_TWICE WHAT IS LOVE","label":"TWICE WHAT IS LOVE","cat":"dance"},
{"name":"d_How You Like That","label":"How You Like That","cat":"dance"},
{"name":"d_Micheal Myer","label":"Micheal Myer","cat":"dance"},
{"name":"d_Shake Body","label":"Shake Body","cat":"dance"},
{"name":"d_2 Phut Hon","label":"2 Phut Hon","cat":"dance"},
{"name":"d_Gangnam Style","label":"Gangnam Style","cat":"dance"},
{"name":"d_Sway Sway","label":"Sway Sway","cat":"dance"},
{"name":"d_Dolphin Dance","label":"Dolphin Dance","cat":"dance"},
{"name":"d_Hakari Dance","label":"Hakari Dance","cat":"dance"},
{"name":"d_Tyla Dance ","label":"Tyla Dance","cat":"dance"},
{"name":"d_LouisianaJigg","label":"LouisianaJigg","cat":"dance"},
{"name":"d_Soda Pop","label":"Soda Pop","cat":"dance"},
{"name":"d_Pennywise","label":"Pennywise","cat":"dance"},
{"name":"d_Hip Sway","label":"Hip Sway","cat":"dance"},
{"name":"d_TWICE LOOK AT ME","label":"TWICE LOOK AT ME","cat":"dance"},
{"name":"d_Twice The Feels","label":"Twice The Feels","cat":"dance"},
{"name":"d_Party Rock Anthem","label":"Party Rock Anthem","cat":"dance"},
{"name":"d_Metro Man Dance","label":"Metro Man Dance","cat":"dance"},
{"name":"d_Koto Nai Meme","label":"Koto Nai Meme","cat":"dance"},
{"name":"d_Haidilao","label":"Haidilao","cat":"dance"},
{"name":"d_Sharp Mj Sway","label":"Sharp Mj Sway","cat":"dance"},
{"name":"d_Samba Dance","label":"Samba Dance","cat":"dance"},
{"name":"d_MonsterMash","label":"MonsterMash","cat":"dance"},
{"name":"d_Thai Remix 1","label":"Thai Remix 1","cat":"dance"},
{"name":"d_FANCY","label":"FANCY","cat":"dance"},
{"name":"d_Rollie","label":"Rollie","cat":"dance"},
{"name":"d_Hit Every Beat","label":"Hit Every Beat","cat":"dance"},
{"name":"d_7Ring Dance","label":"7Ring Dance","cat":"dance"},
{"name":"d_Torture dance","label":"Torture dance","cat":"dance"},
{"name":"d_Hip Dance","label":"Hip Dance","cat":"dance"},
{"name":"d_Teto Terrioty","label":"Teto Terrioty","cat":"dance"},
{"name":"d_Thai Remix 3 Wong wian yai","label":"Thai Remix 3 Wong wian yai","cat":"dance"},
{"name":"d_Hugo Dance","label":"Hugo Dance","cat":"dance"},
{"name":"d_Wednesday Dance","label":"Wednesday Dance","cat":"dance"},
{"name":"d_Piano Hand","label":"Piano Hand","cat":"dance"},
{"name":"d_Shuffling Dance","label":"Shuffling Dance","cat":"dance"},
{"name":"d_ISHOWSPEED","label":"ISHOWSPEED","cat":"dance"},
{"name":"d_Billy Bounce","label":"Billy Bounce","cat":"dance"},
{"name":"d_Vai Toma Phonk","label":"Vai Toma Phonk","cat":"dance"},
{"name":"d_Jax Toy","label":"Jax Toy","cat":"dance"},
{"name":"d_Sturdy","label":"Sturdy","cat":"dance"},
{"name":"d_How Its Done","label":"How Its Done","cat":"dance"},
{"name":"d_Candy Dance","label":"Candy Dance","cat":"dance"},
{"name":"d_Dougie","label":"Dougie","cat":"dance"},
{"name":"d_Dia Delica Phonk","label":"Dia Delica Phonk","cat":"dance"},
{"name":"d_Parrot Party","label":"Parrot Party","cat":"dance"},
{"name":"d_Side To Side","label":"Side To Side","cat":"dance"},
{"name":"d_Golden Huntrix","label":"Golden Huntrix","cat":"dance"},
{"name":"d_Super Bass","label":"Super Bass","cat":"dance"},
{"name":"e_Nyan Cat","label":"Nyan Cat","cat":"emote"},
{"name":"d_Silly Dance","label":"Silly Dance","cat":"dance"},
{"name":"d_Thai Remix 2","label":"Thai Remix 2","cat":"dance"},
{"name":"d_Tenna Dance","label":"Tenna Dance","cat":"dance"},
{"name":"d_Ur Idol Saja Boy ","label":"Ur Idol Saja Boy","cat":"dance"},
{"name":"d_Confess Your Love","label":"Confess Your Love","cat":"dance"},
{"name":"d_Jummum Dance","label":"Jummum Dance","cat":"dance"},
{"name":"d_DARE-Gorillaz","label":"DARE-Gorillaz","cat":"dance"},
{"name":"d_PocoyoDance","label":"PocoyoDance","cat":"dance"},
{"name":"d_DeltaruneJevilidle","label":"DeltaruneJevilidle","cat":"dance"},
{"name":"d_GoofyOrangeCat","label":"GoofyOrangeCat","cat":"dance"},
{"name":"d_jayguapoDance","label":"jayguapoDance","cat":"dance"},
{"name":"d_JasonVorhees","label":"JasonVorhees","cat":"dance"},
{"name":"d_RakaiEmote","label":"RakaiEmote","cat":"dance"},
{"name":"d_FestaNoBrasil","label":"FestaNoBrasil","cat":"dance"},
{"name":"d_SweetFluffyBunnyDance","label":"SweetFluffyBunnyDance","cat":"dance"},
{"name":"d_SHAKETHATTHANG","label":"SHAKETHATTHANG","cat":"dance"},
{"name":"d_MichaelMyers","label":"MichaelMyers","cat":"dance"},
{"name":"d_JasonVorheesDance","label":"JasonVorheesDance","cat":"dance"},
{"name":"d_ThaistyleDJDancing","label":"ThaistyleDJDancing","cat":"dance"},
{"name":"d_hipsway","label":"hipsway","cat":"dance"},
{"name":"e_HornetsSpider","label":"HornetsSpider","cat":"emote"},
{"name":"e_Kidtantrum","label":"Kidtantrum","cat":"emote"},
{"name":"e_MEGAPOOPING","label":"MEGAPOOPING","cat":"emote"},
{"name":"e_ChildishTantrum2","label":"ChildishTantrum2","cat":"emote"},
{"name":"e_IWANNARUNAWAY","label":"IWANNARUNAWAY","cat":"emote"},
{"name":"e_Slow-MoBackflip","label":"Slow-MoBackflip","cat":"emote"},
{"name":"e_ChildishTantrum","label":"ChildishTantrum","cat":"emote"},
{"name":"e_bodyphone","label":"bodyphone","cat":"emote"},
{"name":"e_CryingTantrumSit","label":"CryingTantrumSit","cat":"emote"},
{"name":"e_BoxingCombo","label":"BoxingCombo","cat":"emote"},
{"name":"e_BangHeadonWall","label":"BangHeadonWall","cat":"emote"},
{"name":"e_SHAKE","label":"SHAKE","cat":"emote"},
{"name":"e_SpinningCat","label":"SpinningCat","cat":"emote"},
{"name":"p_ChineseMilitaryDancePose","label":"ChineseMilitaryDancePose","cat":"pose"},
{"name":"p_Swinging","label":"Swinging","cat":"pose"},
{"name":"p_CasualSitting","label":"CasualSitting","cat":"pose"},
{"name":"p_FloatinginLove","label":"FloatinginLove","cat":"pose"},
{"name":"p_CuteSit","label":"CuteSit","cat":"pose"},
{"name":"p_OliviaRodrigoHead","label":"OliviaRodrigoHead","cat":"pose"},
{"name":"p_SleepingSoundly","label":"SleepingSoundly","cat":"pose"},
{"name":"p_Catnap","label":"Catnap","cat":"pose"},
{"name":"p_AngelSleepingOnClouds","label":"AngelSleepingOnClouds","cat":"pose"},
{"name":"p_Floating","label":"Floating","cat":"pose"}];
